citrusframework/citrus

- modules/citrus-core/src/main/java/com/consol/citrus/xml/schema/JarWSDLLocator.java
- modules/citrus-core/src/main/java/com/consol/citrus/xml/schema/WsdlXsdSchema.java
- modules/citrus-integration/src/citrus/java/com/consol/citrus/ws/SendSoapMessageWithAttachmentITest.java
- modules/citrus-integration/src/citrus/resources/citrus-context.xml
- modules/citrus-integration/src/citrus/resources/citrus-schemas-context.xml
- modules/citrus-integration/src/citrus/resources/com/consol/citrus/ws/soapIcon.txt
- modules/citrus-integration/src/citrus/resources/com/consol/citrus/ws/soapImage.txt
- modules/citrus-integration/src/citrus/tests/com/consol/citrus/ws/SendSoapMessageWithMtomAttachmentITest.xml
- modules/citrus-integration/src/main/resources/com/consol/citrus/demo/BookStoreExtened.wsdl
- modules/citrus-model/model-ws/src/main/resources/com/consol/citrus/schema/citrus-ws-testcase-2.0.1.xsd
- modules/citrus-model/model-ws/src/main/resources/com/consol/citrus/schema/citrus-ws-testcase.xsd
- modules/citrus-ws/pom.xml
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/actions/ReceiveSoapMessageAction.java
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/actions/SendSoapMessageAction.java
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/config/xml/SendSoapMessageActionParser.java
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/config/xml/SoapAttachmentParser.java
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/message/SoapAttachment.java
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/message/SoapMessage.java
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/message/converter/SoapMessageConverter.java
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/validation/SimpleSoapAttachmentValidator.java
Bug fixes:
* Support loading of WSDL files and their imports from jar files
Enhancements:
* Support of mtom for attachements (XOP package), new attribute "mtom-enabled" (defaults to false)
* Support mtom xop references and mtom inline data with auto-detection of data type, new attribute "mtom-inline" (defaults to false)
* Binary attachment support (no dynamic data replacement, no string conversion) based on content type
* Improved handling of dynamic content in attachments
* Added "schema-repository" to SendSoapMessageAction to support defining a custom schema repository to resolve mtom attachments
* Added SOAP mtom attachment integration test
Known issue:
* Schema validation for SOAP messages with MTOM attachments (not inline) is not working, because the XOP reference is not valid data. …
> SOAP MTOM attachment support

- modules/citrus-http/src/main/java/com/consol/citrus/http/interceptor/LoggingHandlerInterceptor.java
The response body of an HTTP server was not traced via the MessageTracingTestListener.
The http headers appeared in the trace log, but the body was missing.
To fix the problem, the HttpMessageController was unwrapped from the HandlerMethod object.
> Fix HTTP Server Response Message Tracing

- modules/citrus-core/src/main/java/com/consol/citrus/xml/schema/WsdlXsdSchema.java
- modules/citrus-integration/src/it/java/com/consol/citrus/ws/SoapSchemaValidationIT.java
- modules/citrus-integration/src/it/resources/citrus-schemas-context.xml
- modules/citrus-integration/src/it/resources/com/consol/citrus/schema/SampleServiceWithImportsNamespaceDiff.wsdl
- modules/citrus-integration/src/it/resources/com/consol/citrus/ws/SoapSchemaValidationNamespaceDiffIT.xml
Fixed XML schema validation when namespace of WSDL schema does not match namespace of WSDL. Added sample schema and integration test.
Follow up of pull request #48, commit db116dea881de88150fc2f75ca4301e37f3923bc.
> Fixed XML schema validation, follow up to pull request #48

- modules/citrus-mail/src/main/java/com/consol/citrus/mail/message/MailMessageConverter.java
- modules/citrus-mail/src/main/java/com/consol/citrus/mail/server/MailServer.java
- modules/citrus-ssh/src/main/java/com/consol/citrus/ssh/message/SshMessageConverter.java
- src/docbkx/actions-receive.xml
- src/docbkx/actions-send.xml
I fixed the typo in `paylaod` to `payload`. I am not sure if the exception message in `CitrusRuntimeException` is parsed somewhere, in which case this change could lead to incompatibilities. Otherwise, the change is a very small one.
> Fix typo "paylaod" --> "payload"

- modules/citrus-integration/src/it/java/com/consol/citrus/ws/SendSoapMessageWithAttachmentIT.java
- modules/citrus-integration/src/it/resources/com/consol/citrus/ws/SendSoapMessageWithAttachmentInTemplateIT.xml
- modules/citrus-ws/src/main/java/com/consol/citrus/ws/message/SoapAttachment.java
Problem:
Assume you have a template to upload a file to a SOAP server. The file is given as template parameter variable, and the attachment is a resource using this variable. When you call this twice the second call takes the variable of the first call because it is resolved too early.
Fixed that variables are now resolved on each template call.
> Fixed SOAP attachment handling in template calls

- modules/citrus-mail/src/test/java/com/consol/citrus/mail/server/MailServerTest.java
Fixes date comparisons that were being done on String forms of dates and were sensitive to the timezone of the host machine. Fixed to compare as Date instances, and thereby not be concerned with timezone.
> fixed data comparisons that worked only in UTC+1 timezone

- src/docbkx/soap.xml
After some struggle getting `citrus-ws:server` to work with SOAP 1.2 using the documentation [1], I found the trick after debugging the code and reading an example [2] by adding `root-parent-context="true"` to `citrus-ws:server`.
To save this time for others, I added this line to the documentation
[1] http://citrusframework.org/reference/html/index.html#soap-12
[2] https://github.com/christophd/citrus/blob/master/modules/citrus-ws/src/test/resources/citrus-context.xml
> Added 'root-parent-context' to citrus-ws:server for SOAP1.2

- src/manual/actions-database.md
- src/manual/actions-receive.md
- src/manual/actions-send.md
- src/manual/actions-transform.md
- src/manual/endpoints.md
- src/manual/functions.md
- src/manual/samples-flightbooking.md
- src/manual/soap.md
- src/manual/ssh.md
- src/manual/test-case.md
- src/manual/test-variables.md
- src/manual/validation-xml.md
- src/manual/xpath.md
Text elements describing XML tags (enclosed in '<' and '>') are not displayed in HTML since they are recognized as HTML tags. They must be escaped in Markdown.
> Fix unescaped brackets

- modules/citrus-core/src/main/java/com/consol/citrus/container/Template.java
Spelling improvements for the `Template` class JavaDoc.
> Spelling in JavaDocs and comments

- src/manual/docker.md
- src/manual/ssh.md
Correct spelling of 'daemon' (was 'deamon')
> Correct spelling of 'daemon' (was 'deamon')

- modules/citrus-core/src/main/java/com/consol/citrus/actions/ExecuteSQLQueryAction.java
Change to make it working again with MS SQL when using mixed case column names.
> MS SQL Compatibility fix

- modules/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/builder/SoapClientRequestActionBuilder.java
- modules/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/builder/SoapServerResponseActionBuilder.java
- modules/citrus-java-dsl/src/test/java/com/consol/citrus/dsl/design/SendSoapMessageTestDesignerTest.java
Enabled access to mtomEnabled flag for soap send actions for both client
and server through the java dsl (designer).
So far mtom-enabled could only be set when writing a citrus test in XML.
```
soap(action -> action.client(myClient)
.send().mtomEnabled(true)
.payload(...)
```
> enabled access to mtomEnabled flag for soap send actions in java dsl

- src/manual/setup.md
- src/site/_docs/setup-maven.md
With maven-archetype-3.0.0 it is no longer possible to specify the archetype cataloge via command line switch, which causes the setup to abort with an error.
I updated the Maven setup guide to use Citrus archetypes from Maven central repository to avoid changes in settings.xml for a first try.
> Updated maven setup according to changes in maven-archetype plugin

- modules/citrus-core/src/main/java/com/consol/citrus/context/TestContext.java
- modules/citrus-core/src/test/java/com/consol/citrus/context/TestContextTest.java
Enabled variable substitution for map keys which in turn allows to use Citrus context variable substitution for HTTP header key values.
> Closes #258

- src/manual/changes-2-0.adoc
- src/manual/changes-new.adoc
There were some Markdown style links left in the documentation. I converted them to AsciiDoc style links.
> Ascii links

- modules/citrus-core/src/main/java/com/consol/citrus/config/util/VariableExtractorParserUtil.java
- modules/citrus-core/src/main/java/com/consol/citrus/config/xml/ReceiveMessageActionParser.java
- modules/citrus-core/src/main/java/com/consol/citrus/validation/GenericPayloadVariableExtractor.java
- modules/citrus-core/src/main/java/com/consol/citrus/validation/json/JsonPathMessageValidationContext.java
- modules/citrus-core/src/test/java/com/consol/citrus/config/xml/ReceiveMessageActionParserTest.java
- modules/citrus-http/src/test/java/com/consol/citrus/http/config/xml/HttpReceiveRequestActionParserTest.java
- modules/citrus-http/src/test/java/com/consol/citrus/http/config/xml/HttpReceiveResponseActionParserTest.java
- modules/citrus-integration/src/it/java/com/consol/citrus/variables/UseXPathVariablesIT.java
- modules/citrus-integration/src/it/resources/com/consol/citrus/variables/UseVariablesIT.xml
- modules/citrus-integration/src/it/resources/com/consol/citrus/variables/UseXPathVariablesIT.xml
- modules/citrus-zookeeper/src/main/java/com/consol/citrus/zookeeper/config/xml/ZooExecuteActionParser.java
This PR implements a generic variable extractor which substitutes Citrus test variables at runtime and uses the correct extractor.
This allows to use XPath / JSONPath expression stored in Citrus variables for variable extraction.
> Closes #266

- modules/citrus-core/src/main/java/com/consol/citrus/context/TestContext.java
- modules/citrus-core/src/main/java/com/consol/citrus/testng/AbstractTestNGCitrusTest.java
- modules/citrus-core/src/test/java/com/consol/citrus/context/DataProviderAvailableInVariableBlockTest.java
- modules/citrus-core/src/test/java/com/consol/citrus/context/TestContextTest.java
- modules/citrus-core/src/test/resources/com/consol/citrus/context/DataProviderAvailableInVariableBlockTest.xml
Hi!
I solved #298 by adding the TestNG DataProvider values as variables to the TestContext, as proposed in the Issue by @gucce.
In addition, I added the test case provided in the Issue as an automated test so that this problem will never occur again. I'm not sure whether I met the your expectations concerning the project structure, test coverage and code style.
I'm looking forward to your feedback.
BR,
Sven
> 298 test ng dataprovider parameters cannot be used in variables block

- modules/citrus-core/src/test/java/com/consol/citrus/integration/parameter/TestParameterIT.java
Hi!
As I reviewed your changes, I found that the CitrusXmlTest reference was not changed after renaming the xml file. Therefore the test failed.
> (#298) Fixed CitrusXmlTest reference

- modules/citrus-http/src/main/java/com/consol/citrus/http/message/HttpMessage.java
- modules/citrus-http/src/main/java/com/consol/citrus/http/message/HttpMessageContentBuilder.java
- modules/citrus-http/src/test/java/com/consol/citrus/http/integration/HttpClientTemplateIT.java
- modules/citrus-http/src/test/resources/com/consol/citrus/http/integration/HttpClientTemplateIT.xml
Hi!
This is my attempt to solve #271. 
I found out, that the HttpMessageContentBuilder.buildMessageContent method worked on the initial request defined in the template and therefore replaced all variable placeholders with the concrete values. This led to the observed behavior. 
Now the buildMessageContent method works on a copy of the initial HttpMessage so that it is idempotent concerning the provided message. To create the copy, I had to adapt the copy Constructor of the HttpMessage, because the cookies where not copied if the provided Message was a HttpMessage instance.
In addition I applied some structural changes to the HttpMessageContentBuilder by extracting several methods. The non functional changes have been applied after the actual problem has been solved. So you may want to …
> Update http request variable in template

- README.md
Hi @christophd.
I found out that ```http://www.citrusframework.org/contact.html``` results in a 404. Therefore I exchanged the URL and hope that I've chosen the correct one. ;-)
BR,
Sven
> Fixed link to the consulting info page

- modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/config/annotation/JdbcServerConfig.java
- modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/config/annotation/JdbcServerConfigParser.java
- modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/config/xml/JdbcEndpointConfigurationParser.java
- modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/server/ConnectionValidationQueryPatternMatcher.java
- modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/server/JdbcEndpointAdapterController.java
- modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/server/JdbcEndpointConfiguration.java
- modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/server/JdbcServerBuilder.java
- modules/citrus-jdbc/src/test/java/com/consol/citrus/jdbc/config/xml/JdbcEndpointConfigurationParserTest.java
- modules/citrus-jdbc/src/test/java/com/consol/citrus/jdbc/server/ConnectionValidationQueryPatternMatcherTest.java
- modules/citrus-jdbc/src/test/java/com/consol/citrus/jdbc/server/JdbcEndpointAdapterControllerTest.java
- modules/citrus-jdbc/src/test/resources/com/consol/citrus/jdbc/config/xml/JdbcEndpointConfigurationParserTest-context.xml
- modules/citrus-model/model-jdbc/src/main/resources/com/consol/citrus/schema/citrus-jdbc-config-2.7.5.xsd
- modules/citrus-model/model-jdbc/src/main/resources/com/consol/citrus/schema/citrus-jdbc-config.xsd
- src/manual/jdbc.adoc
- new configuration property 'auto-reply-connection-validation-queries' on jdbc-server introduced
- in case the flag 'auto-reply-connection-validation-queries' is set to true, certain queries are intercepted in the JdbcEndpointAdapterController and are automatically answered by Citrus with a success and an empty data set.
- a new citrus property 'citrus.jdbc.connection.validaiton.queries' introduced. It can be used to provide a list of queries, which has to be automatically answered by Citrus
> #369 Default responses for JDBC requests

- src/manual/http.adoc
Small typo in the HTTP REST documentation.
> Correct typo in HTTP REST client documentation.

- modules/citrus-core/src/main/java/com/consol/citrus/report/JUnitReporter.java
- modules/citrus-core/src/test/java/com/consol/citrus/report/JUnitReporterTest.java
A possible solution, escape test.name and test.error.msg with StringEscapeUtils.escapeXml
> Citrus reports containing invalid XML #428

- modules/citrus-http/src/main/java/com/consol/citrus/http/message/CookieParser.java
- modules/citrus-http/src/main/java/com/consol/citrus/http/message/HttpMessageConverter.java
- modules/citrus-http/src/test/java/com/consol/citrus/http/message/CookieParserTest.java
- modules/citrus-http/src/test/java/com/consol/citrus/http/message/HttpMessageConverterTest.java
- modules/citrus-integration/src/it/java/com/consol/citrus/http/HttpCookieIT.java
Hi!
This PR is based on PR #543 and issue #561 of @kezhuw.
I've added the integration test from the issue to proof, that the fix from the original PR solves the issue of overwritten cookies. In addition, I've added unit tests to the `HttpMessageConverter` based on the current implementation. The only thing I've changed implementation wise is the handling of the `Secure` flag for Cookies, based on the [Mozilla Set-Cookie documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie).
The old implementation expected the Secure flag to be `Secure=true`. I know that the fix is not ideal but I didn't want to change the contract of `getCookieParam`. :sweat_smile: 
To the reviewer: If you want to merge this directly after review, please merge the changes into the …
> 561: Lost cookie entries except the last one + Tests and refactoring

- modules/citrus-http/src/main/java/com/consol/citrus/http/message/HttpMessageConverter.java
Uses `HttpHeaders.add` to append cookie name-value pair instead of `HttpHeaders.set` which dropping old `Cookie` header.
> Fix overwritten cookie in HttpMessageConverter

- src/manual/containers-async.adoc
- src/manual/containers-parallel.adoc
PR concerning #591. 
Added the missing documentation concerning the required mapping of massage actions in parallel and async action containers
> Added missing documentation concerning parallel and async

- modules/citrus-core/src/main/java/com/consol/citrus/condition/ActionCondition.java
- modules/citrus-core/src/main/java/com/consol/citrus/condition/FileCondition.java
- modules/citrus-core/src/main/java/com/consol/citrus/condition/HttpCondition.java
- modules/citrus-core/src/main/java/com/consol/citrus/condition/MessageCondition.java
- modules/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/builder/WaitActionConditionBuilder.java
- modules/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/builder/WaitBuilder.java
- modules/citrus-java-dsl/src/test/java/com/consol/citrus/dsl/builder/WaitBuilderTest.java
Hi!
This PR intends to fix the broken quality gate.
During the reconstruction of the `WaitBuilder` API in #549, the quality gate broke because the reconstruction was now handles as untested *new code*.
Therefore I added test coverage to this class.
I also deprecated the `ms` methods which were a duplicated of `milliseconds`.
> Add WaitBuilderTest

- core/citrus-api/src/main/java/com/consol/citrus/TestCase.java
- core/citrus-api/src/main/java/com/consol/citrus/context/TestContext.java
- core/citrus-base/src/main/java/com/consol/citrus/DefaultTestCase.java
- runtime/citrus-cucumber/src/main/java/com/consol/citrus/cucumber/CitrusLifecycleHooks.java
- runtime/citrus-cucumber/src/test/java/com/consol/citrus/cucumber/backend/CitrusLifecycleHooksTest.java
Make sure to report the Citrus test as failed when the Cucumber scenario is marked as failed. At the same time preserve Citrus failure information when present.
> fix(#715): False positive test report with Cucumber

- core/citrus-base/src/main/java/com/consol/citrus/report/JUnitReporter.java
- core/citrus-base/src/test/java/com/consol/citrus/report/JUnitReporterTest.java
Merged #670 based on https://github.com/tvelkoff/citrus and resolved conflicts
> fix(#669): Avoid Nullpointer in JUnitReporter

- modules/citrus-core/src/main/java/com/consol/citrus/report/JUnitReporter.java
- modules/citrus-core/src/test/java/com/consol/citrus/report/JUnitReporterJunitTest.java
This fixes a bug in the JUnitReporter.
This includes a new JUnit 5 test that identifies the bug. The error occurs when the orElse clause yields a null value and is provided as the value in a put to a Map.
(I've created this test based on the existing TestNG test because I am still unable to get TestNG running in my environment.)
This error surfaced when creating a TestResult using TestResult.failed(String, String, String).
> Citrus Issue 669

- core/citrus-base/src/main/java/com/consol/citrus/util/TestUtils.java
- core/citrus-base/src/test/java/com/consol/citrus/TestCaseTest.java
Explicitly cancel scheduler future, call shutdown, await termination and shutdownNow if necessary. Should not have any active waiting threads then.
> fix: Unit test on thread leak in test case finish

- connectors/citrus-kubernetes/src/main/java/com/consol/citrus/kubernetes/client/KubernetesClientBuilder.java
Closes: https://github.com/citrusframework/citrus/issues/741
> chore: fix the parameter name for namespace

- core/citrus-base/src/main/java/com/consol/citrus/actions/SleepAction.java
- core/citrus-base/src/test/java/com/consol/citrus/actions/SleepActionTest.java
- core/citrus-spring/src/main/java/com/consol/citrus/config/xml/SleepActionParser.java
- core/citrus-spring/src/test/java/com/consol/citrus/config/xml/SleepActionParserTest.java
- Make sure to use seconds time unit when setting "time" attribute on sleep action in XML
- Properly convert seconds, minutes and decimal time values to milliseconds in sleep action
> fix(#775): Fix unit tests on SleepAction XML bean definition parser

- endpoints/citrus-http/src/main/java/com/consol/citrus/http/config/annotation/HttpServerConfig.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/config/annotation/HttpServerConfigParser.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/config/xml/HttpServerParser.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/controller/HttpMessageController.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/interceptor/LoggingHandlerInterceptor.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/server/AbstractHttpServerBuilder.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/server/HttpServer.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/server/HttpServerSettings.java
- endpoints/citrus-http/src/main/java/com/consol/citrus/http/servlet/CitrusDispatcherServlet.java
- endpoints/citrus-http/src/main/resources/com/consol/citrus/schema/citrus-http-config-3.0.0-SNAPSHOT.xsd
- endpoints/citrus-http/src/main/resources/com/consol/citrus/schema/citrus-http-config.xsd
- endpoints/citrus-http/src/test/java/com/consol/citrus/http/config/xml/HttpServerParserTest.java
- endpoints/citrus-http/src/test/resources/com/consol/citrus/http/config/xml/HttpServerParserTest-context.xml
- validation/citrus-validation-json/src/main/java/com/consol/citrus/json/JsonSettings.java
- Introduce map cache with servlet request as key and response as value
- Access cache with servlet request to make sure that multiple handler interceptors get the very same response content
- Introduce cache size to avoid memory issues with long running server instances
- Automatically clear cache when maximum number of responses is reached
This fixes #644 with multiple logging interceptor handlers calling for the response content. All interceptors access the cache with the same servlet request. This makes sure that each interceptor gets access to the very same response content.
The downside is that the in memory cache will grow with every communication on the server. Therefore a maximum cache size has been introduced and a mechanism to automatically free the cache when it is full.
> fix(#644): Cache server responses according to servlet request

- core/citrus-spring/src/main/java/com/consol/citrus/config/xml/AbstractEndpointParser.java
- endpoints/citrus-http/src/test/java/com/consol/citrus/http/config/xml/HttpClientParserTest.java
Legacy Citrus projects may not receive correct bean names according to XML configuration with id attributes set on bean elements. This is because com.consol.citrus.config.ComponentLifecycleProcessor is not set properly. Users must add ComponentLifecycleProcessor manually or benefit from this fix.
> fix: Fix bean names for legacy projects

- endpoints/citrus-http/src/main/java/com/consol/citrus/http/actions/HttpActionBuilder.java
step 1 for `//TODO` in [`HttpScenarioActionBuilder` of citrusframework/citrus-simulator](https://github.com/postfinance/citrus-simulator/blob/a126e9ef4c45669f8196133d4998763daca21731/simulator-starter/src/main/java/com/consol/citrus/simulator/http/HttpScenarioActionBuilder.java#L54).
contributor: @zauggmori.
> bugfix: use super-interface endpoint in HttpActionBuilder

- runtime/citrus-junit5/src/main/java/com/consol/citrus/junit/jupiter/spring/CitrusSpringExtension.java
one must call the `afterAll` delegate as well. this was introduced to [`CitrusExtension`](https://github.com/citrusframework/citrus/blame/main/runtime/citrus-junit5/src/main/java/com/consol/citrus/junit/jupiter/CitrusExtension.java#L80) in b52b025158046d4b21c89dd93a4ebf1d72461121.
> fix: spring extension after all callback

- connectors/citrus-sql/src/main/java/com/consol/citrus/actions/AbstractDatabaseConnectingTestAction.java
- core/citrus-api/src/main/java/com/consol/citrus/container/TestActionContainer.java
- core/citrus-api/src/main/java/com/consol/citrus/context/TestContext.java
- core/citrus-base/src/main/java/com/consol/citrus/DefaultTestCase.java
- core/citrus-base/src/main/java/com/consol/citrus/actions/AbstractTestAction.java
- core/citrus-base/src/main/java/com/consol/citrus/container/AbstractActionContainer.java
- core/citrus-base/src/main/java/com/consol/citrus/container/AbstractIteratingActionContainer.java
- core/citrus-base/src/main/java/com/consol/citrus/container/Assert.java
- core/citrus-base/src/main/java/com/consol/citrus/container/Async.java
- core/citrus-base/src/main/java/com/consol/citrus/container/Catch.java
- core/citrus-base/src/main/java/com/consol/citrus/container/Conditional.java
- core/citrus-base/src/main/java/com/consol/citrus/container/Parallel.java
- core/citrus-base/src/main/java/com/consol/citrus/container/Sequence.java
- core/citrus-base/src/main/java/com/consol/citrus/container/Timer.java
- core/citrus-base/src/test/java/com/consol/citrus/container/AsyncTest.java
- core/citrus-base/src/test/java/com/consol/citrus/report/FailureStackTestListenerTest.java
- endpoints/citrus-ws/src/main/java/com/consol/citrus/ws/actions/AssertSoapFault.java
- runtime/citrus-testng/src/test/java/com/consol/citrus/integration/container/CustomContainerJavaIT.java
- vintage/citrus-java-dsl/src/test/java/com/consol/citrus/dsl/runner/CustomContainerTestRunnerTest.java
- vintage/citrus-java-dsl/src/test/java/com/consol/citrus/integration/design/CustomContainerJavaIT.java
- vintage/citrus-java-dsl/src/test/java/com/consol/citrus/integration/runner/CustomContainerTestRunnerIT.java
… when evaluating test action done state
- Evaluation of done state visits all entries in the list of executed actions in order to verify that the action is done
- Concurrently some action may finish and as a result the action gets added to the list of executed actions which eventually causes concurrent modification exception
- Make sure to iterate over a copy of executed actions list to avoid concurrent modification exception
- Separate active action and executed actions handling where active action state is set before execution while action is added to the list of executed actions after execution
- Also use active action and executed action list in test containers to evaluate done state properly (e.g. when there is still an active action pending in execution)
- Properly account for …
> fix(#879): Avoid concurrent modification exception 

- connectors/citrus-sql/src/test/java/com/consol/citrus/integration/actions/QueryDatabaseRetriesJavaIT.java
- connectors/citrus-sql/src/test/resources/com/consol/citrus/integration/actions/QueryDatabaseRetriesIT.xml
- endpoints/citrus-http/src/test/resources/citrus-context.xml
- endpoints/citrus-jms/src/test/resources/citrus-activemq-context.xml
- endpoints/citrus-ws/src/test/resources/citrus-context.xml
- tools/archetypes/jms/src/main/resources/archetype-resources/src/test/resources/citrus-context.xml
- vintage/citrus-java-dsl/src/test/resources/citrus-context.xml
For some reason temporary queues get deleted before the synchronous JMS consumer is able to send a reply message. The error can not be reproduced on local machines but only happens randomly on GitHub CI jobs. Try to overcome this by disabling advisory support and explicitly set the timeout for purging temporary destinations on the JMS broker.
Also fixed SQL query retries tests eliminating racing conditions when inserting/deleting entries from database.
> chore(build): Fix flaky CI job tests

- core/citrus-spring/src/main/java/com/consol/citrus/functions/DefaultFunctionLibraryFactory.java
- core/citrus-spring/src/main/java/com/consol/citrus/functions/FunctionConfig.java
- core/citrus-spring/src/main/java/com/consol/citrus/functions/core/EnvironmentPropertyFunction.java
- core/citrus-spring/src/test/java/com/consol/citrus/functions/DefaultFunctionLibraryFactoryTest.java
- core/citrus-spring/src/test/java/com/consol/citrus/functions/core/EnvironmentPropertyFunctionTest.java
Make sure to properly set Spring environment and application context on all functions in default function library. Adding factory bean for default function library that is aware of application context and Spring environment for proper dependency injection. Also, automatically add all functions to the function library that live as Spring beans in the application context.
Use traditional system environment variable settings lookup as fallback when Spring environment is not set properly.
Fixes #894
> fix(#894): Avoid NullpointerException in citrus:env function

- core/citrus-base/src/main/java/com/consol/citrus/actions/PurgeEndpointAction.java
- core/citrus-base/src/main/java/com/consol/citrus/endpoint/adapter/mapping/SimpleMappingStrategy.java
- core/citrus-spring/src/main/java/com/consol/citrus/CitrusSpringContext.java
- core/citrus-spring/src/main/java/com/consol/citrus/config/CitrusSpringConfig.java
- core/citrus-spring/src/main/java/com/consol/citrus/functions/FunctionConfig.java
- core/citrus-spring/src/main/java/com/consol/citrus/reporter/ReporterConfig.java
- core/citrus-spring/src/main/java/com/consol/citrus/validation/matcher/ValidationMatcherConfig.java
- core/citrus-spring/src/test/java/com/consol/citrus/TestSuiteTest.java
- Enable reference resolver in PurgeEndpointAction for bean postprocessing
- Use "citrus" prefix for all default beans in CitrusSpringConfig (avoid name clash with other libraries being loaded into the application context)
- Support building CitrusContext from application context that has no default Citrus beans configured (avoids NullpointerException in JUnit5 extension)
> chore: Spring context improvements

- validation/citrus-validation-json/src/main/java/com/consol/citrus/dsl/JsonSupport.java
- validation/citrus-validation-json/src/main/java/com/consol/citrus/validation/json/JsonMappingValidationProcessor.java
- validation/citrus-validation-json/src/main/java/com/consol/citrus/validation/json/JsonPathMessageValidator.java
- validation/citrus-validation-json/src/test/java/com/consol/citrus/actions/dsl/ReceiveMessageActionBuilderTest.java
- validation/citrus-validation-json/src/test/java/com/consol/citrus/integration/JsonMappingValidationProcessorIT.java
- validation/citrus-validation-json/src/test/java/com/consol/citrus/integration/JsonPathExpressionValidationIT.java
- validation/citrus-validation-json/src/test/java/com/consol/citrus/integration/JsonPathVariableExtractorIT.java
- validation/citrus-validation-xml/src/main/java/com/consol/citrus/validation/xml/XpathMessageValidator.java
- validation/citrus-validation-xml/src/test/java/com/consol/citrus/integration/ValidateXpathJavaIT.java
- Make sure to also support multiple validate() calls in Java DSL in order to have multiple jsonPath validations
- Consolidate multiple validation contexts to single context in JsonPathMessageValidator
- Also apply same logic for xpath validation Java DSL
- Fix JsonSupport static entrance method for Json object mapping validation
- Add some unit tests
Fixes #892 
Closes #898
> fix(#892): Support multiple jsonPath validations

- core/citrus-api/src/main/java/com/consol/citrus/CitrusSettings.java
- core/citrus-api/src/main/java/com/consol/citrus/message/Message.java
- core/citrus-api/src/main/java/com/consol/citrus/message/MessagePayloadUtils.java
- core/citrus-api/src/main/java/com/consol/citrus/validation/DefaultEmptyMessageValidator.java
- core/citrus-api/src/test/java/com/consol/citrus/message/MessagePayloadUtilsTest.java
- core/citrus-base/src/main/java/com/consol/citrus/actions/ReceiveMessageAction.java
- core/citrus-base/src/main/java/com/consol/citrus/actions/ReceiveTimeoutAction.java
- core/citrus-base/src/test/java/com/consol/citrus/message/DefaultMessageTest.java
- endpoints/citrus-http/src/test/java/com/consol/citrus/http/validation/TextEqualsMessageValidator.java
- runtime/citrus-groovy/src/test/java/com/consol/citrus/validation/TextEqualsMessageValidator.java
- runtime/citrus-xml/src/test/java/com/consol/citrus/validation/TextEqualsMessageValidator.java
- runtime/citrus-yaml/src/test/java/com/consol/citrus/validation/TextEqualsMessageValidator.java
- validation/citrus-validation-json/src/main/java/com/consol/citrus/validation/json/JsonTextMessageValidator.java
- validation/citrus-validation-text/src/main/java/com/consol/citrus/validation/text/PlainTextMessageValidator.java
- validation/citrus-validation-xml/src/main/java/com/consol/citrus/validation/xml/DomXmlMessageValidator.java
- Make sure to log received message content independently of validator applied
- Remove message content logging from validator implementations and move to receive message action
- Also makes sure to always apply log modifier (e.g. masking sensitive data such as passwords)
- Pretty print XML and Json payload with just pure Java tooling
Fixes #846 
Closes #891
> fix(#846): Always debug log received message content

- core/citrus-base/src/main/java/com/consol/citrus/DefaultTestCase.java
- core/citrus-base/src/main/java/com/consol/citrus/common/DefaultTestLoader.java
- core/citrus-base/src/test/java/com/consol/citrus/TestCaseTest.java
- runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/GroovyTestLoader.java
- vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/junit/JUnit4CitrusTest.java
- vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/junit/JUnit4CitrusTestDesigner.java
- vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/junit/jupiter/CitrusExtension.java
- vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/testng/TestNGCitrusTest.java
- vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/testng/TestNGCitrusTestDesigner.java
- Avoid success reports for failing tests in DefaultTestLoader
- Makes sure to call `runner.stop()` after test result has been set on exception handling
- Avoid duplicate test reports when `test.execute()` and `runner.stop()` both calling `test.finish()`
- Move `test.finish()` invocation to test loader
Fixes #924
> fix(#924): Fix false positive test report in DefaultTestLoader

- runtime/citrus-junit5/src/main/java/com/consol/citrus/junit/jupiter/CitrusExtension.java
Changed the suite name passed to beforeSuite and afterSuite callbacks to the actual class or method name and also passed the tags of the current test case or method to the call. The default Citrus suite name that comes from a constant will still be used as fallback.
Related issue: #934
> Citrus w/ jUnit5: Neither an actual suite name nor groups are passed to BeforeSuites / AfterSuites shouldExecute method

- connectors/citrus-docker/pom.xml
- endpoints/citrus-mail/pom.xml
- endpoints/citrus-mail/src/main/java/org/citrusframework/mail/client/MailClient.java
- endpoints/citrus-mail/src/main/java/org/citrusframework/mail/client/MailEndpointConfiguration.java
- endpoints/citrus-mail/src/main/java/org/citrusframework/mail/client/MailSender.java
- endpoints/citrus-mail/src/main/java/org/citrusframework/mail/message/MailMessageConverter.java
- endpoints/citrus-mail/src/main/java/org/citrusframework/mail/server/MailServer.java
- endpoints/citrus-mail/src/test/java/org/citrusframework/mail/client/MailClientTest.java
- endpoints/citrus-mail/src/test/java/org/citrusframework/mail/config/annotation/MailClientConfigParserTest.java
- endpoints/citrus-mail/src/test/java/org/citrusframework/mail/config/xml/MailClientParserTest.java
- endpoints/citrus-mail/src/test/java/org/citrusframework/mail/server/MailServerTest.java
- endpoints/citrus-mail/src/test/resources/org/citrusframework/mail/integration/MailServerAcceptIT.xml
- endpoints/citrus-mail/src/test/resources/org/citrusframework/mail/integration/MailServerErrorIT.xml
- endpoints/citrus-ws/pom.xml
- pom.xml
- tools/pom.xml
- tools/test-generator/pom.xml
Compatibility fixes for
the [citrusframework/citrus-simulator](https://github.com/citrusframework/citrus-simulator) project. These changes - mostly in `citrus-jms` and `citrus-mail` - will allow it to build on jdk17 and with the latest Spring- and Boot framework as well.
Progress originally reported in PR: https://github.com/citrusframework/citrus-simulator/pull/163#issuecomment-1657058339.
> citrus-simulator compatibility fixes

- validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonPathVariableExtractor.java
- validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/XpathPayloadVariableExtractor.java
you already have access to `fromHeaders` and `fromBody`, but not for JSON or XPaths.
> feat: static access to extractor builders

- core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
I came up with a solution that enables the complete disablement of the LoggingReporter's functionality. Considering that both the HtmlReporter and JUnitReporter already offer similar disablement options, I believe this solution adequately addresses the requirements.
> feat(#973): Allow deactivation of standard LoggingReporter

- src/manual/validation-hamcrest.adoc
- validation/citrus-validation-hamcrest/src/main/java/org/citrusframework/validation/matcher/hamcrest/HamcrestValidationMatcher.java
- validation/citrus-validation-hamcrest/src/test/java/org/citrusframework/validation/matcher/hamcrest/HamcrestValidationMatcherTest.java
I am pleased to provide the following fix for [Issue 341](https://github.com/citrusframework/citrus/issues/341).
As stated in the issue the problem here are the comma and bracket chars in the matcher expression. They cannot be parsed into the correct matcher parameters using the simple approach, splitting by ','.
Note that for the specific case, the matcher text needs to be put in '', as it contains '(' and ''' characters which would otherwise interfere with the parameter extraction algorithm.
That said, the following expression:
```
allOf(startsWith('INSERT INTO todo_entries (id, title, description, done)'))
```
Would perfectly match this string:
```
INSERT INTO todo_entries (id, title, description, done) values (1, 'Invite for meeting', 'Invite the group for a lunch meeting', 'false') …
```
> fix(#341): Allow comma and brackets in matcher expressions

- endpoints/citrus-http/src/main/java/org/citrusframework/http/actions/HttpClientResponseActionBuilder.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/actions/HttpServerResponseActionBuilder.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/controller/HttpMessageController.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessage.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessageConverter.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageConverterTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageTest.java
- tools/test-generator/src/main/java/org/citrusframework/generate/provider/http/HttpCodeProvider.java
- tools/test-generator/src/main/java/org/citrusframework/generate/provider/http/ReceiveHttpResponseActionProvider.java
- tools/test-generator/src/main/java/org/citrusframework/generate/provider/http/SendHttpResponseActionProvider.java
- tools/test-generator/src/test/java/org/citrusframework/generate/provider/http/HttpCodeProviderTest.java
This pull request will fix [Issue 978](https://github.com/citrusframework/citrus/issues/978). There are a few breaking changes because `HttpMessage` uses now `HttpStatusCode` instead of the `HttpStatus` enum. I also removed the `HttpMessage.statusCode(Integer)` and the `HttpMessage.status(HttpStatus)` method because they are no longer necessary. `HttpMessage.getStatusCode()` returns now a `HttpStatusCode` instead of a `HttpStatus`.
> fix(#978): Allow custom http status codes

- core/citrus-spring/src/main/java/org/citrusframework/reporter/ReporterConfig.java
- core/citrus-spring/src/test/java/org/citrusframework/UnitTestSupport.java
- core/citrus-spring/src/test/java/org/citrusframework/reporter/DisabledReporterConfigTest.java
- core/citrus-spring/src/test/java/org/citrusframework/reporter/OverrideReporterConfigTest.java
- core/citrus-spring/src/test/java/org/citrusframework/reporter/ReporterConfigTest.java
- src/manual/reporting.adoc
The requested feature has been implemented as follows: when you add an override implementation of a Reporter through Spring Configuration, it will automatically suppress the default Citrus reporter. Additionally, if you set the enablement property to 'false,' the Reporter will also be suppressed.
Please note that not all Reporters can be disabled due to Autowiring requirements, and there may be limitations on adding additional reporters through single bean matching. For me it makes most sense, to just override an existing Reporter with an own implementation.
If you have any comments or further requests, feel free to comment.
> feat(#976): Disable/Override standard Citrus reporters

- validation/citrus-validation-hamcrest/src/main/java/org/citrusframework/validation/matcher/hamcrest/HamcrestValidationMatcher.java
- validation/citrus-validation-hamcrest/src/test/java/org/citrusframework/validation/matcher/hamcrest/HamcrestValidationMatcherTest.java
Adds the **matcherPattern** Hamcrest matcher for regular expressions.
> fix(#988): Add Hamcrest matchesPattern matcher

- connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLQueryAction.java
- connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecuteSQLQueryActionTest.java
- connectors/citrus-sql/src/test/resources/org/citrusframework/actions/test-sql-query-statements.sql
> allow WITH sql keyword for query action

- catalog/citrus-bom/pom.xml
- pom.xml
- runtime/citrus-quarkus/citrus-quarkus-deployment/pom.xml
- runtime/citrus-quarkus/citrus-quarkus-deployment/src/main/java/org/citrusframework/quarkus/deployment/CitrusProcessor.java
- runtime/citrus-quarkus/citrus-quarkus-deployment/src/main/resources/META-INF/LICENSE.txt
- runtime/citrus-quarkus/citrus-quarkus-deployment/src/main/resources/META-INF/NOTICE.txt
- runtime/citrus-quarkus/citrus-quarkus-it/pom.xml
- runtime/citrus-quarkus/citrus-quarkus-it/src/main/java/org/citrusframework/quarkus/app/DemoApplication.java
- runtime/citrus-quarkus/citrus-quarkus-it/src/main/resources/META-INF/LICENSE.txt
- runtime/citrus-quarkus/citrus-quarkus-it/src/main/resources/META-INF/NOTICE.txt
- runtime/citrus-quarkus/citrus-quarkus-it/src/main/resources/application.properties
- runtime/citrus-quarkus/citrus-quarkus-it/src/test/java/org/citrusframework/quarkus/app/DemoApplicationTest.java
- runtime/citrus-quarkus/citrus-quarkus-it/src/test/java/org/citrusframework/quarkus/app/validation/TextEqualsMessageValidator.java
- runtime/citrus-quarkus/citrus-quarkus-runtime/pom.xml
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/java/org/citrusframework/quarkus/CitrusSupport.java
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/java/org/citrusframework/quarkus/CitrusTestResource.java
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/resources/META-INF/LICENSE.txt
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/resources/META-INF/NOTICE.txt
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/resources/quarkus-extension.yaml
- runtime/citrus-quarkus/pom.xml
- runtime/pom.xml
- Enable Citrus support for QuarkusTest framework
- Add Citrus Quarkus test resource that takes care of Citrus resource injection and Citrus test lifecycle management as part of a Quarkus test
- Add CitrusSupport annotation to enable Citrus for a Quarkus test
> fix(#993): Add QuarkusTest runtime support

- core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
This is a fix for Issue 1003. Parallel test execution revealed, a synchronization issue in  ResourcePathTypeResolver.
> fix(#1003): Synchronize access to the zipEntries array cache

- connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecutePLSQLAction.java
- connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLAction.java
- connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLQueryAction.java
- connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecutePLSQLActionTest.java
- connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecuteSQLActionTest.java
- connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecuteSQLQueryActionTest.java
- connectors/citrus-sql/src/test/java/org/citrusframework/actions/dsl/ExecuteSQLQueryTestActionBuilderTest.java
one must explicitly call `extract` using column- plut target-variable-names in order to extract data from the result into the current `TestContext`.
BREAKING CHANGE: sql queries no longer automatically extract variables
> chore: remove automatic sql variable extraction

- .mvn/wrapper/maven-wrapper.properties
- CONTRIBUTING.md
- README.md
- connectors/citrus-selenium/pom.xml
- pom.xml
- runtime/citrus-quarkus/pom.xml
- tools/archetypes/jms/src/main/resources/archetype-resources/pom.xml
- tools/archetypes/quickstart/src/main/resources/archetype-resources/pom.xml
- tools/archetypes/soap/src/main/resources/archetype-resources/pom.xml
updates most dependencies to the latest versions. PATCH or MINOR updates only.
intentionally removed: `com.google.guava:guava` - unused.
intentionally excluded, because it is known to cause problems with jackson:
* `org.yaml:snakeyaml` ............................... 2.0 -> 2.2
left out breaking changes:
* `jetty` from 11 to 12.
* https://github.com/citrusframework/citrus/issues/1010
* `org.apache.xmlbeans:xmlbeans` from 3.0.0 to 5.1.1
* https://github.com/citrusframework/citrus/issues/1011
* `io.swagger:swagger-core` to `io.swagger.core.v3:swagger-core`
* https://github.com/citrusframework/citrus/issues/1012
I will submit this separately with a bit more careful testing.
remaining updates, some of them breaking and NOT final (therefore not done). I also didn't check the version ranges in …
> update dependency versions

- pom.xml
it avoids to be affected to CVE-2023-44487
https://blog.vespa.ai/cve-2023-44487/
> Upgrade Jetty from 11.0.16 to 11.0.17

- connectors/citrus-docker/pom.xml
- connectors/citrus-kubernetes/pom.xml
- pom.xml
it has the main benefit to not have anymore a dependency on Netty
In getting started of docker-java, they are mentioning to use docker-java-core (and not docker-java): https://github.com/docker-java/docker-java/blob/main/docs/getting_started.md#dependencies
(it is comforting me in the fact that it should work nicely)
> Slim down dependency from docker-java to docker-java-core

- core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
Citrus does not "mvnw verify" on windows any more.
Looking into  the following commit, one can see, that the code was not correctly adjusted for this change. 
[See 6b163eb](https://github.com/citrusframework/citrus/commit/6b163eb115814935a87cb81f8e0da5e91fb1fe6a#r130779285)
The problem occurs, when passing an empty string into resolveAllFromJar. Passing the fullPath variable solves the issue because   getFullResourcePath handles empty paths.
> fix: Do not resolveAllFromJar on empty path

- endpoints/citrus-ssh/pom.xml
- pom.xml
fix reported [CVE-2023-33201](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-33201) in `cprov-jdk15on`. migrated to `bcprov-jdk18on` in the process.
> vulnerability in bouncycastle

- connectors/citrus-selenium/src/test/java/org/citrusframework/selenium/groovy/AbstractGroovyActionDslTest.java
- connectors/citrus-selenium/src/test/java/org/citrusframework/selenium/xml/AbstractXmlActionTest.java
- connectors/citrus-selenium/src/test/java/org/citrusframework/selenium/yaml/AbstractYamlActionTest.java
- connectors/citrus-sql/src/test/java/org/citrusframework/sql/groovy/AbstractGroovyActionDslTest.java
- connectors/citrus-sql/src/test/java/org/citrusframework/sql/xml/AbstractXmlActionTest.java
- connectors/citrus-sql/src/test/java/org/citrusframework/sql/yaml/AbstractYamlActionTest.java
- core/citrus-base/src/main/java/org/citrusframework/CitrusContext.java
- core/citrus-base/src/main/java/org/citrusframework/annotations/CitrusAnnotations.java
- endpoints/citrus-camel/src/test/java/org/citrusframework/camel/groovy/AbstractGroovyActionDslTest.java
- endpoints/citrus-camel/src/test/java/org/citrusframework/camel/xml/AbstractXmlActionTest.java
- endpoints/citrus-camel/src/test/java/org/citrusframework/camel/yaml/AbstractYamlActionTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/groovy/AbstractGroovyActionDslTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/xml/AbstractXmlActionTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/yaml/AbstractYamlActionTest.java
- endpoints/citrus-jms/src/test/java/org/citrusframework/jms/groovy/AbstractGroovyActionDslTest.java
- endpoints/citrus-jms/src/test/java/org/citrusframework/jms/xml/AbstractXmlActionTest.java
- endpoints/citrus-jms/src/test/java/org/citrusframework/jms/yaml/AbstractYamlActionTest.java
- endpoints/citrus-spring-integration/src/test/java/org/citrusframework/springintegration/groovy/AbstractGroovyActionDslTest.java
- endpoints/citrus-spring-integration/src/test/java/org/citrusframework/springintegration/xml/AbstractXmlActionTest.java
- endpoints/citrus-spring-integration/src/test/java/org/citrusframework/springintegration/yaml/AbstractYamlActionTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/groovy/AbstractGroovyActionDslTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/xml/AbstractXmlActionTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/yaml/AbstractYamlActionTest.java
- runtime/citrus-groovy/src/test/java/org/citrusframework/groovy/dsl/AbstractGroovyActionDslTest.java
- runtime/citrus-groovy/src/test/java/org/citrusframework/groovy/xml/AbstractXmlActionTest.java
- runtime/citrus-groovy/src/test/java/org/citrusframework/groovy/yaml/AbstractYamlActionTest.java
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/java/org/citrusframework/quarkus/CitrusTestResource.java
- runtime/citrus-xml/src/test/java/org/citrusframework/xml/actions/AbstractXmlActionTest.java
- runtime/citrus-yaml/src/test/java/org/citrusframework/yaml/actions/AbstractYamlActionTest.java
- Make sure to parse configuration classes for a Citrus instance in an idempotent way
- Do not load configuration multiple times as it may lead to port binding errors for server components
Fixes #1055
> fix(#1055): Avoid duplicate loading of configuration classes

- core/citrus-base/src/main/java/org/citrusframework/functions/core/ChangeDateFunction.java
- core/citrus-base/src/test/java/org/citrusframework/functions/core/ChangeDateFunctionTest.java
I managed to land exactly at a second while testing:
```shell
[ERROR] Tests run: 800, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 49.82 s <<< FAILURE! - in TestSuite
[ERROR] testFunction(org.citrusframework.functions.core.ChangeDateFunctionTest)  Time elapsed: 0.012 s  <<< FAILURE!
java.lang.AssertionError: expected [2024-12-19 10:04:06] but found [2024-12-19 10:04:07]
at org.citrusframework.functions.core.ChangeDateFunctionTest.testFunction(ChangeDateFunctionTest.java:118)
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ChangeDateFunctionTest.testFunction:118 expected [2024-12-19 10:04:06] but found [2024-12-19 10:04:07]
[INFO]
[ERROR] Tests run: 800, Failures: 1, Errors: 0, Skipped: 0
```
> ci: fix flaky date function test

- core/citrus-base/src/main/java/org/citrusframework/variable/dictionary/AbstractDataDictionary.java
- core/citrus-base/src/test/java/org/citrusframework/variable/dictionary/AbstractDataDictionaryTest.java
why did nobody tell me that `ClasspathResource`'s don't have a `File`? 😉 
fixes https://github.com/citrusframework/citrus-simulator/pull/219.
> fix: data dictionary resolve for classpath resources

- core/citrus-api/src/main/java/org/citrusframework/spi/PropertiesLoader.java
- core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
- core/citrus-base/src/main/java/org/citrusframework/variable/dictionary/AbstractDataDictionary.java
- core/citrus-spring/src/main/java/org/citrusframework/spi/CitrusResourceWrapper.java
- core/citrus-spring/src/test/java/org/citrusframework/spi/CitrusResourceWrapperTest.java
after https://github.com/citrusframework/citrus/pull/1067 I figured that it'd be best to centralize property loading, so errors can be minimalized in the future.
additionally, classpath resources seem to require special treatment in the citrus/spring resource wrapper. that has been done poorly so far.
with this the [citrusframework/citrus-simulator builds on `4.1.0-SNAPSHOT`](https://github.com/citrusframework/citrus-simulator/pull/219). I think it would be fair to release `4.0.2` as soon as possible @christophd.
> chore: citrus resource wrapper for classpath resources

- endpoints/citrus-jms/src/main/java/org/citrusframework/jms/config/annotation/JmsEndpointConfigParser.java
- endpoints/citrus-jms/src/main/java/org/citrusframework/jms/config/annotation/JmsSyncEndpointConfigParser.java
- endpoints/citrus-jms/src/test/java/org/citrusframework/jms/config/annotation/JmsEndpointConfigParserExceptionTest.java
- endpoints/citrus-jms/src/test/java/org/citrusframework/jms/config/annotation/JmsSyncEndpointConfigParserExceptionTest.java
- Removed the `connectionFactory` related exception throwing.
- Move exception throwing in case of jms template and destination/destination name combination to the proper `if` block.
- Added unit tests for the exception flows of both parser classes.
> #1066: Improve validation and test coverage for JmsEndpointConfigParser and JmsSyncEndpointConfigParser

- connectors/citrus-sql/src/test/java/org/citrusframework/actions/dsl/ExecutePLSQLTestActionBuilderTest.java
- connectors/citrus-sql/src/test/java/org/citrusframework/actions/dsl/ExecuteSQLTestActionBuilderTest.java
- core/citrus-base/src/main/java/org/citrusframework/actions/AbstractAsyncTestAction.java
- core/citrus-base/src/main/java/org/citrusframework/actions/SendMessageAction.java
- core/citrus-base/src/main/java/org/citrusframework/util/FileUtils.java
- core/citrus-base/src/test/java/org/citrusframework/actions/ReceiveMessageBuilderTest.java
- core/citrus-base/src/test/java/org/citrusframework/actions/dsl/ReceiveMessageActionBuilderTest.java
- core/citrus-base/src/test/java/org/citrusframework/actions/dsl/SendMessageActionBuilderTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/actions/dsl/AssertSoapFaultBuilderTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/actions/dsl/ReceiveSoapMessageTestActionBuilderTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/actions/dsl/SendSoapFaultTestActionBuilderTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/actions/dsl/SendSoapMessageTestActionBuilderTest.java
- runtime/citrus-groovy/src/test/java/org/citrusframework/actions/dsl/GroovyTestActionBuilderTest.java
- runtime/citrus-testng/src/test/java/org/citrusframework/actions/dsl/ParallelTestActionBuilderTest.java
- runtime/citrus-testng/src/test/java/org/citrusframework/actions/dsl/ReceiveMessageTestActionBuilderTest.java
- runtime/citrus-testng/src/test/java/org/citrusframework/actions/dsl/SendMessageTestActionBuilderTest.java
- validation/citrus-validation-groovy/src/test/java/org/citrusframework/actions/dsl/ExecuteSQLQueryTestActionBuilderTest.java
- validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonTextMessageValidator.java
- validation/citrus-validation-json/src/test/java/org/citrusframework/actions/dsl/ReceiveMessageActionBuilderTest.java
- validation/citrus-validation-xml/src/test/java/org/citrusframework/actions/dsl/ReceiveMessageActionBuilderTest.java
[chore: Fix Json field reference in validation error message](https://github.com/citrusframework/citrus/commit/de14e49557a564df5dcf648e9a3ade336b1cdf41)
[chore: Avoid hiding exceptions in forked actions](https://github.com/citrusframework/citrus/commit/68bf8e2fd0a7d2644bb5d31e66b73088dacedbf7)
[chore: Avoid NPE when reading file content of resource that does not exist](https://github.com/citrusframework/citrus/commit/ff55371a7069b65a7cace99323ef2231f3ed54c7)
> Collection of minor improvements

- src/manual/runtimes-cucumber.adoc
The verification step should contain the expected message and not add extra text.
> Removed extra text in the verification message.

- endpoints/citrus-http/pom.xml
- endpoints/citrus-http/src/main/java/org/citrusframework/http/actions/HttpServerActionBuilder.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/actions/HttpServerActionBuilderTest.java
after some discussions in https://github.com/citrusframework/citrus-simulator/pull/221 and https://github.com/citrusframework/citrus-simulator/pull/224, I've decided to move the response helpers into citrus nonetheless.
cc: @novarx.
> feat(citrus-http): easy json response helpers

- src/manual/functions.adoc
- Added missing parameter information for the `encodeBase64`, `decodeBase64` and `jsonPath` functions.
- Added a new section for the `unixTimestamp` function.
> #1086: Extend Citrus functions documentation

- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/client/KubernetesClientBuilder.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/CredentialValidator.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/annotation/KubernetesClientConfig.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/annotation/KubernetesClientConfigParser.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/xml/KubernetesClientParser.java
- connectors/citrus-kubernetes/src/main/resources/org/citrusframework/schema/citrus-kubernetes-config.xsd
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/CredentialValidatorTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/annotation/KubernetesBadClientConfigParserTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/annotation/KubernetesClientConfigParserTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/xml/KubernetesBadClientParserTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/xml/KubernetesClientParserTest.java
- connectors/citrus-kubernetes/src/test/resources/citrus-context.xml
- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/config/xml/KubernetesBadClientParserTest-context.xml
- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/config/xml/KubernetesClientParserTest-context.xml
- src/manual/endpoint-kubernetes.adoc
- Allow configuration with new oauthToken
- Update Tests
- Update Documentation
> feat(#1089): kubernetes client config with auth token

- src/manual/endpoint-camel.adoc
- src/manual/endpoint-channel.adoc
- src/manual/endpoint-soap.adoc
- src/manual/functions.adoc
- src/manual/setup.adoc
- fixed some incorrect link formatting
- typo fixes
- fixes for incorrect class names, method signatures and formatting in code snippets
Closes #1105.
> Documentation fixes

- validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/DomXmlMessageValidator.java
- validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/schema/XmlSchemaValidation.java
- validation/citrus-validation-xml/src/test/java/org/citrusframework/validation/xml/DomXmlMessageValidatorTest.java
in addition to https://github.com/citrusframework/citrus/pull/1093, so it's possible to override the validation style from children/callees.
> allow configuration of xml validator via constructor

- core/citrus-api/src/main/java/org/citrusframework/spi/Resources.java
- core/citrus-api/src/test/java/org/citrusframework/spi/ResourcesTest.java
- core/citrus-api/src/test/resources/ResourcesTest/FileWithContent.json
Fixes issue #1100:
An UrlResource pointing to an existing but empty file must return true on exist.
Also added a couple of tests.
> fix(#1100): empty file resource returns true on exist

- runtime/citrus-cucumber/src/main/java/org/citrusframework/cucumber/CitrusLifecycleHooks.java
- runtime/citrus-cucumber/src/main/java/org/citrusframework/cucumber/backend/CitrusBackend.java
- Do not use Cucumber before/after annotations as part of CitrusLifecycleHooks as this may lead to errors when loading the class with normal glue code API
- CitrusLifecycleHooks are only supposed to be loaded by the special Citrus backend implementation
Fixes #1116 
Fixes #1047
> fix(#1116): Fix CitrusLifecycleHooks to not break Cucumber API

- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/resources/META-INF/quarkus-extension.yaml
It's usually not necessary to add scm information to the quarkus-extension.yaml. Although https://quarkus.io/version/main/guides/extension-metadata#quarkus-extension-yaml does show an scm entry, it's in the 'this is what gets generated after the tooling enriches the data' section. Because the citrus pom.xml has scm information, we can be DRY and omit it from the metadata.
(I've also realised the example format in the docs is wrong, so the `scm:` information here is being ignored anyway, but that's a separate issue!)
> Remove scm information from quarkus-extension.yaml

- core/citrus-api/src/main/java/org/citrusframework/context/TestContext.java
- core/citrus-api/src/test/java/org/citrusframework/context/TestContextUnitTest.java
> gracefully shutdown test context

- .github/workflows/build.yml
- .github/workflows/lts.yml
- .github/workflows/release.yml
- core/citrus-spring/src/test/java/com/consol/citrus/BeanDefinitionParserTestSupport.java
- core/citrus-spring/src/test/java/com/consol/citrus/UnitTestSupport.java
- pom.xml
- runtime/citrus-cucumber/src/test/java/com/consol/citrus/cucumber/UnitTestSupport.java
- runtime/citrus-testng/src/main/java/com/consol/citrus/testng/TestNGCitrusSupport.java
- runtime/citrus-testng/src/main/java/com/consol/citrus/testng/spring/TestNGCitrusSpringSupport.java
- utils/citrus-test-support/src/main/java/com/consol/citrus/testng/AbstractTestNGUnitTest.java
- vintage/citrus-java-dsl/src/main/java/com/consol/citrus/testng/AbstractTestNGCitrusTest.java
- vintage/citrus-java-dsl/src/test/java/com/consol/citrus/dsl/UnitTestSupport.java
backport fix of a4a1a5daec800cfc070c9df1135db958df31e1ad for citrus `v3.4.0`. bug has originally been reported in #1090.
closes #1146.
[`support/3.0.0`](https://github.com/citrusframework/citrus/tree/support/3.0.0) is at e8382c98e49b3d14476f31ae5aa7980161d150f6, which is [`v3.4.0`](https://github.com/citrusframework/citrus/releases/tag/v3.4.0)
> backport[`v3.4.0`]: update testng to v7.10.1

- core/citrus-api/src/main/java/org/citrusframework/CitrusSettings.java
- core/citrus-base/src/main/java/org/citrusframework/message/DefaultMessage.java
- core/citrus-base/src/test/java/org/citrusframework/message/DefaultMessageTest.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessage.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessageBuilder.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageBuilderTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageTest.java
I've updated the HttpMessageBuilder to consistently generate messages with new IDs and timestamps. As a result, messages created by the builder will always have unique identifiers and may differ in their timestamps. I haven't identified any scenarios where this change would cause any issues.
I would appreciate Christoph's thorough review and expert opinion on this matter, considering the potential for unforeseen side effects.
> fix(#1143): let HttpMessageBuilder create messages with unique ids

- core/citrus-base/src/main/java/com/consol/citrus/report/LoggingReporter.java
Avoid all test steps to be reported as "TEST STEP 0" for incremental tests
(cherry picked from commit 21aeb4385587cae7a35911a517f41b372189d53d)
> fix(#948): Log proper test step index on incremental Citrus tests

- validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonTextMessageValidator.java
- validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/schema/JsonSchemaValidation.java
- validation/citrus-validation-json/src/test/java/org/citrusframework/validation/json/JsonTextMessageValidatorTest.java
we have a custom JSON validator and want to construct the error message in the same format as the original: https://github.com/citrusframework/citrus/pull/1154/files#diff-f9be5af8b22ec2ff3b7b516d047768e9d3bdbfaea29748310aaa76ff125b6600R89.
> json message validator access

- src/manual/validation-json.adoc
- validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonElementValidator.java
- validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonElementValidatorItem.java
- validation/citrus-validation-json/src/test/java/org/citrusframework/validation/json/JsonElementValidatorTest.java
See #1157
A follow up to https://github.com/citrusframework/citrus/pull/1102
It seems that not validating the order of json arrays if `strict` is not the desired behaviour.
see https://github.com/citrusframework/citrus/pull/1102#discussion_r1458473481
> fix: validate json array order if strict mode

- core/citrus-api/src/main/java/org/citrusframework/TestResult.java
revert some changes introduced within https://github.com/citrusframework/citrus/pull/1149 - they broke the simulator.
> fix: test result compatibility for simulator

- endpoints/citrus-http/src/main/java/org/citrusframework/http/actions/HttpClientActionBuilder.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/actions/HttpClientResponseActionBuilder.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/actions/HttpClientActionBuilderTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/actions/HttpClientResponseActionBuilderTest.java
Http Message actions should use interface `HttpStatusCode` instead of concrete implementation `HttpStatus`. otherwise, custom response codes are not allowed.
> fix(citrus-http): accept status code interface

- connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/actions/OpenApiClientRequestActionBuilder.java
- connectors/citrus-openapi/src/test/java/org/citrusframework/openapi/actions/OpenApiClientRequestMessageBuilderTest.java
- connectors/citrus-openapi/src/test/resources/org/citrusframework/openapi/petstore/petstore-derivation-for-message-builder-test.json
When generating the request message, random data is used for the payload and for parameters - even when values are explicitly specified. I changed this behavior to prefer explicitly declared values and to skip random data generation in this case.
Resolves #1168
> Fix: use explicitly declared values instead of random values (OpenAPI)

- core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
- core/citrus-base/src/main/java/org/citrusframework/main/scan/AbstractTestScanner.java
- core/citrus-base/src/main/java/org/citrusframework/main/scan/JarFileTestScanner.java
While updating `citrus-remote` to Citrus version 4 (https://github.com/citrusframework/citrus-remote/issues/5), we encountered the problem of test classes within a JAR not being loaded.
These changes have been tested by:
1. Installing: https://github.com/maletic/citrus/tree/fix-test-classes-not-found-in-jar
2. Installing: https://github.com/maletic/citrus-remote/tree/update-citrus-remote-to-newest
3. Running: https://github.com/maletic/citrus-playground/tree/update-citrus-remote
> fix: Make tests loadable even from within jar (needed for citrus-remote update to Citrus version 4)

- endpoints/citrus-mail/src/main/java/org/citrusframework/mail/server/MailServer.java
- endpoints/citrus-mail/src/test/java/org/citrusframework/mail/server/MailServerTest.java
closes #1199.
@e17gpy I wen't for this implementation and will skip this part (as reported):
> As the Citrus MailServerBuilder does not have functions to set the host manually, and the MailServer initialises the GreenMail server with a hardcoded host value of null, the Citrus MailServer will only bind to the loopback interface and not receive Mails from another interfaces.
I think for security reasons this is ok. whoever want's to bind to a specific interface should create a custom `MailServer` and use that - with the provided fix this is now possible. does this fit your needs?
> fix(#1199): respect custom mailserver on startup

- runtime/citrus-quarkus/citrus-quarkus-it/pom.xml
- runtime/citrus-quarkus/pom.xml
Align `quarkus-jacoco` with the platform version. I've also included it in the `citrus-quarkus-it` project in order to verify the integration.
> fix quarkus-jacoco

- core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
- runtime/citrus-quarkus/citrus-quarkus-it/pom.xml
- runtime/citrus-quarkus/citrus-quarkus-it/src/test/java/org/citrusframework/quarkus/app/DemoApplicationTest.java
`CodeSource#getLocation` is not annotated as `@Nullable`, but the documentation says:
> Returns: the location (URL), or null if no URL was supplied during construction.
> fix `citrus-quarkus-it`

- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaConsumer.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaEndpoint.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaEndpointConfiguration.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageConsumerUtils.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageFilter.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageFilteringConsumer.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageSingleConsumer.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaProducer.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/selector/KafkaMessageByHeaderSelector.java
- pom.xml
as a cleanup for https://github.com/citrusframework/citrus/pull/1217.
cc: @tschlat we had a little discussion going on about lombok and decided not to use it for the moment. mainly because some companies have stricter rules than we do regarding lombok and prohibit the use of it or any libraries that include it. we will ask the community for their input at a given time.
> fix(citrus-kafka): delombok module

- core/citrus-api/src/test/java/org/citrusframework/spi/AbstractReferenceResolverAwareTestActionBuilderTest.java
- core/citrus-base/src/main/java/org/citrusframework/TestCaseRunnerFactory.java
- core/citrus-base/src/test/java/org/citrusframework/TestCaseRunnerFactoryTest.java
- core/citrus-base/src/test/java/org/citrusframework/actions/ReceiveMessageBuilderTest.java
- core/citrus-base/src/test/java/org/citrusframework/functions/core/ChangeDateFunctionTest.java
- core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
- core/citrus-base/src/test/java/org/citrusframework/sharding/ShardingConfigurationTest.java
- endpoints/citrus-kafka/src/main/resources/org/citrusframework/schema/citrus-kafka-config-4.4.0-SNAPSHOT.xsd
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/integration/KafkaEndpointJavaIT.java
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/integration/KafkaEndpointXmlIT.java
- pom.xml
- Fix Maven build due to embedded Kafka broker starting before old broker has been fully stopped
- Avoids "Address already in use" errors on fast machines
- Remove DirtiesContext for Kafka integration tests to avoid embedded Kafka broker being restarted for each test
- Remove obsolete org.springframework.boot:spring-boot-starter-test dependency in favor of using Citrus ReflectionHelper utils
- Fix citrus-kafka-config-4.4.0-SNAPSHOT.xsd missing changes
> fix: Maven build for citrus-kafka failing

- .github/workflows/build.yml
- .github/workflows/lts.yml
enabled parallel build using the "threads per core" flag: `-T1C`. build ens up being pretty stable running around 12 minutes.
closes #943.
> enable parallel maven build

- .gitignore
- endpoints/citrus-camel/pom.xml
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/CamelSettings.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/AbstractCamelJBangAction.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/CamelActionBuilder.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/CamelJBangActionBuilder.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/CamelRunIntegrationAction.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/CamelStopIntegrationAction.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/CamelVerifyIntegrationAction.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/dsl/CamelSupport.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/jbang/CamelJBang.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/jbang/CamelJBangSettings.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/xml/Camel.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/xml/JBang.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/yaml/Camel.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/yaml/CamelActionBuilderWrapper.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/yaml/JBang.java
- endpoints/citrus-camel/src/test/java/org/citrusframework/camel/integration/CamelJBangIT.java
- endpoints/citrus-camel/src/test/java/org/citrusframework/camel/xml/JBangTest.java
- endpoints/citrus-camel/src/test/java/org/citrusframework/camel/yaml/JBangTest.java
- endpoints/citrus-camel/src/test/resources/org/citrusframework/camel/integration/route.yaml
- endpoints/citrus-camel/src/test/resources/org/citrusframework/camel/xml/camel-jbang-test.xml
- endpoints/citrus-camel/src/test/resources/org/citrusframework/camel/yaml/camel-jbang-test.yaml
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase-4.4.0-SNAPSHOT.xsd
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase.xsd
- Run and stop Camel integrations via JBang
- Add action to verify Camel integration status and its output
> chore(citrus-camel): Add Camel JBang support

- endpoints/citrus-ws/src/main/java/org/citrusframework/ws/client/WebServiceEndpointConfiguration.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/client/WebServiceEndpointConfigurationTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/client/WsTestUtils.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/config/annotation/WebServiceClientConfigParserTest.java
- endpoints/citrus-ws/src/test/java/org/citrusframework/ws/config/xml/WebServiceClientParserTest.java
**problem**; access to `interceptors` list is exposed to public. modifications to it won't be propagated to the underlying web service template.
I personally find this a bit irritating. I think the acessor methods could be used instead, that's what this PR would change.
see [this (unchanged) setter implementation](https://github.com/citrusframework/citrus/pull/1237/files#diff-e9300a011f3d44e61f8d81ccc215c373a1ba8d4163639f765e914e79d5dbd06eR240):
```java
public void setInterceptors(List<ClientInterceptor> interceptors) {
this.interceptors = interceptors;
getWebServiceTemplate().setInterceptors(interceptors.toArray(new ClientInterceptor[0]));
}
```
> fix: disallow access into ws interceptors

- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/integration/KafkaEndpointJavaIT.java
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/integration/KafkaEndpointXmlIT.java
- endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/integration/KafkaEndpointIT_selectiveMessage.xml
especially the `<repeat-onerror-until-true />` should make the test reliable. single-threadding is for reducing side-effects.
closes #1234.
> fix flaky kafka selective xml test

- validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/DomXmlMessageValidator.java
instead of catching ValidationException and only logging the XML message in the catch there, the message is logged every time it is validated.
> fix: message to be validated is logged

- endpoints/citrus-http/src/main/java/org/citrusframework/http/client/HttpClientBuilder.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/client/HttpEndpointConfiguration.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/config/annotation/HttpClientConfig.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/config/annotation/HttpClientConfigParser.java
- endpoints/citrus-http/src/main/java/org/citrusframework/http/config/xml/HttpClientParser.java
- endpoints/citrus-http/src/main/resources/org/citrusframework/schema/citrus-http-config.xsd
- endpoints/citrus-http/src/test/java/org/citrusframework/http/config/annotation/HttpClientConfigParserTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/config/xml/HttpClientParserTest.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/integration/HttpClientWithRedirectIT.java
- endpoints/citrus-http/src/test/resources/citrus-context.xml
- endpoints/citrus-http/src/test/resources/org/citrusframework/http/citrus-http-with-redirect-servlet.xml
- endpoints/citrus-http/src/test/resources/org/citrusframework/http/config/xml/HttpClientParserTest-context.xml
- endpoints/citrus-http/src/test/resources/org/citrusframework/http/integration/HttpClientWithRedirectDisabledIT.xml
- endpoints/citrus-http/src/test/resources/org/citrusframework/http/integration/HttpClientWithRedirectIT.xml
Implement enhancement on HttpClient as described in issue #1243.
> feat(#1243): Add option to configure disable redirect for HttpClient

- pom.xml
- runtime/citrus-quarkus/pom.xml
* activemq to 2.38.0
* apache camel to 4.8.1
* byte-buddy to 1.15.7
* httpclient to 5.4.1
* jackson to 2.18.1
* junit to 5.11.3 and platform to 1.11.3
* mockito to 5.14.2
* spring to 3.0.2 and integration to 6.3.5
* xbean-spring to 4.26
* zookeeper to 3.9.3
> fix(desp): multiple dependency updates

- endpoints/citrus-http/src/main/java/org/citrusframework/http/interceptor/LoggingClientInterceptor.java
- endpoints/citrus-http/src/test/java/org/citrusframework/http/interceptor/LoggingClientInterceptorTest.java
Get encoding charset from HTTP headers or fallback to UTF-8
> Issue #929: fix set charset for request content

- core/citrus-base/src/main/java/org/citrusframework/DefaultTestCase.java
- core/citrus-base/src/main/java/org/citrusframework/common/DefaultTestLoader.java
- core/citrus-base/src/main/java/org/citrusframework/container/Parallel.java
- core/citrus-spring/src/main/java/org/citrusframework/common/SpringXmlTestLoader.java
- runtime/citrus-groovy/src/main/java/org/citrusframework/groovy/GroovyTestLoader.java
- runtime/citrus-xml/src/main/java/org/citrusframework/xml/XmlTestLoader.java
- runtime/citrus-yaml/src/main/java/org/citrusframework/yaml/YamlTestLoader.java
- Avoid test false positives when errors such as ClassNotFoundError are the cause of the test failure
> chore: Catch all errors to avoid loosing failures

- core/citrus-base/src/main/java/org/citrusframework/validation/matcher/DefaultValidationMatcherLibrary.java
- core/citrus-base/src/main/java/org/citrusframework/validation/matcher/core/UuidV4ValidationMatcher.java
- core/citrus-base/src/test/java/org/citrusframework/validation/matcher/core/UuidV4ValidationMatcherTest.java
added validation matcher which checks if value is a UUID v4
> feat: uuid v4 validation matcher

- connectors/citrus-jbang-connector/src/main/java/org/citrusframework/jbang/JBangSupport.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/CamelRunIntegrationAction.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/jbang/CamelJBangSettings.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/xml/Camel.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/xml/JBang.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/yaml/JBang.java
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase-4.4.0-SNAPSHOT.xsd
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase.xsd
- Allow to set system properties and environment variables when running Camel JBang integrations
> chore(camel): Support system properties and envVars on Camel JBang

- core/citrus-api/src/main/java/org/citrusframework/CitrusSettings.java
- core/citrus-api/src/main/java/org/citrusframework/TestClass.java
- core/citrus-api/src/main/java/org/citrusframework/common/TestLoader.java
- core/citrus-base/src/main/java/org/citrusframework/common/JavaTestLoader.java
- core/citrus-base/src/main/resources/META-INF/citrus/test/loader/java
- runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/CitrusTestFactorySupport.java
- runtime/citrus-junit5/src/test/java/org/citrusframework/junit/jupiter/integration/java/JavaTestLoader_IT.java
- runtime/citrus-junit5/src/test/resources/org/citrusframework/junit/jupiter/integration/java/JavaTest.java
- runtime/citrus-junit5/src/test/resources/org/citrusframework/junit/jupiter/simple/DelayTest.java
- runtime/citrus-junit5/src/test/resources/org/citrusframework/junit/jupiter/simple/EchoTest.java
- runtime/citrus-testng/src/main/java/org/citrusframework/testng/TestNGCitrusSupport.java
- runtime/citrus-testng/src/main/java/org/citrusframework/testng/TestNGEngine.java
- runtime/citrus-testng/src/main/java/org/citrusframework/testng/main/TestNGCitrusTest.java
- Allows Citrus JBang to run Java code as a test
- Java code just needs to implement Runnable interface
> chore: Add Java test loader implementation

- core/citrus-base/src/main/java/org/citrusframework/validation/matcher/core/UuidV4ValidationMatcher.java
- runtime/citrus-testng/src/test/java/org/citrusframework/integration/validation/UuidV4ValidationMatcherIT.java
- runtime/citrus-testng/src/test/resources/org/citrusframework/integration/validation/UuidV4ValidationMatcherIT.xml
- src/manual/validation-matchers.adoc
in addition to https://github.com/citrusframework/citrus/pull/1248.
> uuid v4 validation matcher (docs)

- connectors/citrus-sql/src/main/java/org/citrusframework/actions/AbstractDatabaseConnectingTestAction.java
- connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecutePLSQLAction.java
- connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLAction.java
- connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLQueryAction.java
- connectors/citrus-sql/src/main/java/org/citrusframework/sql/xml/Plsql.java
- connectors/citrus-sql/src/main/java/org/citrusframework/sql/xml/Sql.java
- connectors/citrus-sql/src/main/java/org/citrusframework/sql/yaml/Plsql.java
- connectors/citrus-sql/src/main/java/org/citrusframework/sql/yaml/Sql.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/postgresql/PostgreSQLSettings.java
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase-4.4.0-SNAPSHOT.xsd
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase.xsd
- Auto resolve data source from Citrus bean registry
- Allow to set data source by its name in the bean registry
> chore: SQL data source handling

- core/citrus-base/src/main/java/org/citrusframework/AbstractIteratingContainerBuilder.java
- core/citrus-base/src/main/java/org/citrusframework/container/AbstractIteratingActionContainer.java
- core/citrus-base/src/main/java/org/citrusframework/container/RepeatOnErrorUntilTrue.java
- core/citrus-base/src/test/java/org/citrusframework/container/AbstractIteratingActionContainerTest.java
- core/citrus-base/src/test/java/org/citrusframework/container/RepeatOnErrorUntilTrueTest.java
- core/citrus-spring/src/main/java/org/citrusframework/config/xml/AbstractIteratingTestContainerFactoryBean.java
- core/citrus-spring/src/main/java/org/citrusframework/config/xml/AbstractIterationTestActionParser.java
- core/citrus-spring/src/main/java/org/citrusframework/config/xml/RepeatOnErrorUntilTrueParser.java
- core/citrus-spring/src/main/resources/org/citrusframework/schema/citrus-testcase.xsd
- core/citrus-spring/src/test/java/org/citrusframework/config/xml/IterateParserTest.java
- core/citrus-spring/src/test/java/org/citrusframework/config/xml/RepeatOnErrorUntilTrueParserTest.java
- core/citrus-spring/src/test/java/org/citrusframework/config/xml/RepeatUntilTrueParserTest.java
- core/citrus-spring/src/test/resources/org/citrusframework/config/xml/IterateParserTest-context.xml
- core/citrus-spring/src/test/resources/org/citrusframework/config/xml/RepeatOnErrorUntilTrueParserTest-context.xml
- core/citrus-spring/src/test/resources/org/citrusframework/config/xml/RepeatUntilTrueParserTest-context.xml
- endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/integration/KafkaEndpointIT_selectiveMessage.xml
- endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/integration/KafkaEndpointIT_singleMessage.xml
as promised, a timeout implementation on all iterating actions. this is currently:
* repeat until condition
* repeat on error
* iterate
this will partially help with https://github.com/citrusframework/citrus/issues/1258, because the kafka IT's won't run forever.
> add timeout to iterating action containers

- endpoints/citrus-http/src/main/java/org/citrusframework/http/yaml/Http.java
- endpoints/citrus-http/src/test/resources/org/citrusframework/http/yaml/http-client-test.yaml
- endpoints/citrus-http/src/test/resources/org/citrusframework/http/yaml/http-server-test.yaml
- Making it possible to set validate expressions when verifying Http request/response in YAML DSL
> fix: Set validate expressions on Http YAML DSL

- connectors/citrus-testcontainers/pom.xml
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/actions/StartTestcontainersAction.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/LocalStackContainer.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/StartLocalStackAction.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/quarkus/LocalStackContainerResource.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/quarkus/LocalStackContainerSupport.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/kafka/quarkus/KafkaContainerResource.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/kafka/quarkus/KafkaContainerSupport.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/quarkus/ContainerLifecycleListener.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/quarkus/GenericContainerProvider.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/quarkus/GenericContainerResource.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/quarkus/TestcontainersResource.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/quarkus/TestcontainersSupport.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/redpanda/quarkus/RedpandaContainerResource.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/redpanda/quarkus/RedpandaContainerSupport.java
- connectors/citrus-testcontainers/src/test/java/org/citrusframework/testcontainers/integration/StartGenericTestcontainersIT.java
- pom.xml
- runtime/citrus-quarkus/citrus-quarkus-it/src/main/java/org/citrusframework/quarkus/app/DemoApplication.java
- runtime/citrus-quarkus/citrus-quarkus-it/src/main/resources/application.properties
- runtime/citrus-quarkus/citrus-quarkus-it/src/test/java/org/citrusframework/quarkus/app/DemoApplicationTest.java
- runtime/citrus-quarkus/citrus-quarkus-it/src/test/resources/application.properties
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/java/org/citrusframework/quarkus/ApplicationPropertiesSupplier.java
- runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/java/org/citrusframework/quarkus/CitrusTestResource.java
- runtime/citrus-quarkus/pom.xml
- src/manual/runtimes-quarkus.adoc
- Easily add Testcontainers instance to your Quarkus test using annotation based config
- Enable users to access Testcontainers instance after container has been started/stopped via listeners
- Enable users to supply application properties to the Quarkus application under test (e.g. set connection settings from Testcontainers instance)
> Add Quarkus Testcontainers test resource

- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/KubernetesActorTest.java
- Make sure to run the Kubernetes actor unit test in single threaded mode in order to not influence other tests running in parallel
- Make sure to properly reset the actor's connected state after the tests
> fix(1290): Fix flaky Kubernetes actor tests

- core/citrus-api/src/main/java/org/citrusframework/messaging/AbstractMessageConsumer.java
- core/citrus-api/src/main/java/org/citrusframework/messaging/AbstractSelectiveMessageConsumer.java
- core/citrus-base/src/main/java/org/citrusframework/internal/GitHubIssue.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/config/xml/KafkaEndpointParser.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaConsumer.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaEndpoint.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaEndpointConfiguration.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageFilteringConsumer.java
- endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageSingleConsumer.java
- endpoints/citrus-kafka/src/main/resources/org/citrusframework/schema/citrus-kafka-config.xsd
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/config/xml/KafkaEndpointParserTest.java
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/endpoint/KafkaConsumerTest.java
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/endpoint/KafkaEndpointTest.java
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/integration/KafkaEndpointFactoryIT.java
- endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/integration/KafkaEndpointJavaIT.java
- endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/config/xml/KafkaEndpointParserTest-context.xml
- endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/integration/KafkaEndpointIT_selectiveMessage.xml
- endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/integration/KafkaEndpointIT_singleMessage.xml
- src/manual/endpoint-kafka.adoc
> kafka concurrent access

- src/manual/functions.adoc
- validation/citrus-validation-json/pom.xml
- validation/citrus-validation-json/src/main/java/org/citrusframework/functions/core/EscapeJsonFunction.java
- validation/citrus-validation-json/src/test/java/org/citrusframework/functions/core/EscapeJsonFunctionUnitTest.java
Add escapeJson() function and test. Update Citrus doc.
> feat(function): add EscapeJsonFunction, test and doc

- core/citrus-api/src/main/java/org/citrusframework/report/TestResults.java
- core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
- core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
- Make sure to print total test duration in milliseconds
- Improve test report summary logs
> fix(#1302): Fix total test duration report

- core/citrus-base/src/main/java/org/citrusframework/container/Template.java
I want to know _which_ template was successfully executed.
> chore: include template name in success message

- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/actions/CreateServiceAction.java
- core/citrus-api/src/main/java/org/citrusframework/spi/SimpleReferenceResolver.java
- core/citrus-base/src/main/java/org/citrusframework/CitrusContext.java
- core/citrus-base/src/main/java/org/citrusframework/annotations/CitrusAnnotations.java
- core/citrus-base/src/main/java/org/citrusframework/container/AbstractTestBoundaryActionContainer.java
- Make sure parallel running tests are able to add beans to the Citrus registry
- Add null check when adding beans as it makes no sense to add null values to the registry
> chore: Support concurrent Citrus bean registry access

- core/citrus-api/src/main/java/org/citrusframework/context/TestContext.java
- core/citrus-api/src/main/java/org/citrusframework/report/TestListener.java
- core/citrus-api/src/main/java/org/citrusframework/report/TestListeners.java
- core/citrus-api/src/main/java/org/citrusframework/report/TestReporters.java
- core/citrus-api/src/test/java/org/citrusframework/context/TestContextUnitTest.java
- core/citrus-api/src/test/java/org/citrusframework/report/TestReportersTest.java
- core/citrus-base/src/main/java/org/citrusframework/DefaultTestCase.java
- core/citrus-base/src/main/java/org/citrusframework/report/AbstractTestListener.java
- core/citrus-base/src/main/java/org/citrusframework/report/HtmlReporter.java
- core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
- core/citrus-base/src/main/java/org/citrusframework/report/MessageTracingTestListener.java
- core/citrus-base/src/test/java/org/citrusframework/DefaultTestCaseTest.java
- core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
- core/citrus-base/src/test/java/org/citrusframework/report/MessageTracingTestListenerTest.java
- tools/restdocs/src/main/java/org/citrusframework/restdocs/http/CitrusRestDocConfigurer.java
- tools/restdocs/src/main/java/org/citrusframework/restdocs/soap/CitrusRestDocSoapConfigurer.java
[Related issue.](https://github.com/citrusframework/citrus/issues/1218)
The following methods have been added to the TestListener interface:
```java
default void onTestEnd(TestCase test)
default void onFinalActionsEnd(TestCase test)
default void onAfterSequenceBeforeTest(TestCase test)
default void onAfterSequenceAfterTest(TestCase test)
default void onBeforeSequenceBeforeTest(TestCase test)
default void onBeforeSequenceAfterTest(TestCase test)
```
Tests have been written in DefaultCaseTest
> feat(#1218): add events on TestListener

- core/citrus-api/src/main/java/org/citrusframework/report/TestListener.java
Does it make sense to invoke the deprecated `onTestFinish()` in new `onTestExecutionStart()`? I guess onTestFinish method would be called twice as the new `onTestExecutionEnd()` does also call the deprecated method, too.
> fix: Fix duplicate invocation of deprecated onTestFinish callback

- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/KubernetesSettings.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/actions/AbstractKubernetesAction.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/actions/KubernetesActionBuilder.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/actions/ServiceConnectAction.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/actions/ServiceDisconnectAction.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/functions/ResolveExternalServiceUrlFunction.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/functions/ResolveServiceUrlFunction.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/xml/Connect.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/xml/Disconnect.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/xml/Kubernetes.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/yaml/Connect.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/yaml/Disconnect.java
- connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/yaml/Kubernetes.java
- connectors/citrus-kubernetes/src/main/resources/META-INF/citrus/function/resolveExternalServiceUrl
- connectors/citrus-kubernetes/src/main/resources/META-INF/citrus/function/resolveServiceUrl
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/functions/ResolveExternalServiceUrlFunctionTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/functions/ResolveServiceUrlFunctionTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/xml/ServiceConnectTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/xml/ServiceDisconnectTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/yaml/ServiceConnectTest.java
- connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/yaml/ServiceDisconnectTest.java
- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/xml/service-connect-test.xml
- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/xml/service-disconnect-test.xml
- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/yaml/service-connect-test.yaml
- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/yaml/service-disconnect-test.yaml
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase-4.6.0-SNAPSHOT.xsd
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase.xsd
- Uses port forward to connect a local port with an exposed port on a service and pod running on Kubernetes
- Enables users to invoke the Kubernetes service from the local host
> chore: Add test action to connect to a Kubernetes service

- core/citrus-api/src/main/java/org/citrusframework/report/TestResults.java
- core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
- core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
- core/citrus-base/src/test/java/org/citrusframework/report/TestResultsTest.java
Fix the report statistics calculation for skipped tests.
> fix(#1327): Properly report statistics on skipped tests

- core/citrus-api/src/main/java/org/citrusframework/message/MessagePayloadUtils.java
- core/citrus-base/src/main/java/org/citrusframework/actions/ReceiveMessageAction.java
- core/citrus-base/src/test/java/org/citrusframework/actions/ReceiveMessageActionTest.java
- validation/citrus-validation-json/src/test/java/org/citrusframework/actions/dsl/ReceiveMessageActionBuilderTest.java
**edit:** moved bug documentation to: https://github.com/citrusframework/citrus/issues/1338.
closes https://github.com/citrusframework/citrus/issues/1338.
> fix(citrus-base): assume most common message types before validation

- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/ClientFactory.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/LocalStackContainer.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/StartLocalStackAction.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/client/DynamoDbClientFactory.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/client/EventBridgeClientFactory.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/client/KinesisClientFactory.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/client/S3ClientFactory.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/client/SnsClientFactory.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/aws2/client/SqsClientFactory.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/xml/Start.java
- connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/yaml/Start.java
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase-4.7.0-SNAPSHOT.xsd
- runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase.xsd
- src/manual/connector-testcontainers.adoc
- Client factory supporting options to auto create entities for the service
- Auto create S3 buckets, SQS queues, SNS topics, Kinesis streams, ...
> fix(#1353): Introduce LocalStack service client options

- connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/actions/OpenApiServerResponseActionBuilder.java
- connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/OasModelHelper.java
- connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java
- connectors/citrus-openapi/src/test/java/org/citrusframework/openapi/model/v3/Oas30ModelHelperTest.java
previously only inline schemas were supported by validation. this commit enables validation by referenced types.
e.g., instead of
```yaml
headers:
Ping-Time:
required: false
description: response time
schema:
type: integer
format: int64
```
you could now also validate this
```yaml
headers:
$ref: 'Ping-Time'
```
---
note by the author (me): oas 3 is out since 2011 and stable since 2017. I refuse to implement something for oas 2 ⛪
> fix(#1175): openapi validation with references

- core/citrus-api/src/main/java/org/citrusframework/endpoint/DefaultEndpointFactory.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/AbstractCamelAction.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/context/CamelReferenceResolver.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/endpoint/CamelEndpointComponent.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/endpoint/CamelProducer.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/endpoint/CamelSyncProducer.java
- endpoints/citrus-camel/src/main/java/org/citrusframework/camel/util/CamelUtils.java
- endpoints/citrus-camel/src/test/java/org/citrusframework/camel/util/CamelUtilsTest.java
- Auto propagate beans from Citrus registry to Camel registry
- Resolves Camel bean references in endpoint uris and propagates beans from Citrus to the Camel registry
> chore: Add propagation of beans to Camel registry

- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesExecuteIT.xml
- connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesSendReceiveIT.xml
- endpoints/citrus-mail/src/main/java/org/citrusframework/mail/server/MailServer.java
- pom.xml
- Bumped multiple dependencies to their latest versions, including:
- spring → 6.2.9
- spring-boot → 3.4.1
- jackson → 2.19.2
- cucumber → 7.27.0
- testcontainers → 1.21.3
- mockito → 5.18.0
- And others across Apache, Jetty, Netty, Jakarta, Vert.x, etc.
- Deprecated `MailServer.accept(String, List<MailAddress>)` in favor of a new overload accepting a `Set<MailAddress>`.
> update dependencies and deprecate MailServer.accept(List)

- core/citrus-api/pom.xml
- core/citrus-api/src/main/java/org/citrusframework/CitrusSettings.java
- core/citrus-api/src/test/java/org/citrusframework/CitrusSettingsTest.java
- core/citrus-base/src/main/java/org/citrusframework/common/DefaultTestLoader.java
- core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
- core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
- core/citrus-spring/src/main/java/org/citrusframework/reporter/ReporterConfig.java
- core/citrus-spring/src/test/java/org/citrusframework/reporter/ReporterConfigIT.java
- pom.xml
- runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/CitrusExtension.java
- runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/CitrusJUnitException.java
stacktraces pollute test logs in case of errors.
error message should be good enough in most cases. and stacktraces should only occur in technical errors, not test errors.
`LogginReporter` has now property to disable printing stacktraces. can also be activated in spring-based tests, using `citrus.default.logging.reporter.print-stack-traces=false`.
> feat: optionally disable stacktrace printing

- connectors/citrus-openapi/pom.xml
- endpoints/citrus-mail/pom.xml
- pom.xml
detected incompatibility in `citrus-mail` dependency, whenever `citrus-openapi` is also available on the classpath.
with this commits, https://github.com/citrusframework/citrus-simulator/pull/315 is finally mergeable.
additionally fixes reported `https://github.com/advisories/GHSA-fghv-69vj-qj49`.
original MR: https://github.com/citrusframework/citrus/pull/1399.
> critical dependency update + citrusframework/citrus-simulator fix
