citrusframework/citrus

modules/citrus-mail/src/main/java/com/consol/citrus/mail/message/MailMessageConverter.java

Fix #74: MailMessageConverter stopped on empty line

---

modules/citrus-core/src/main/java/com/consol/citrus/channel/ChannelSyncProducer.java

Must be "Message to send is" instead of "Message to sent is"

Typo in debug message

---

src/docbkx/validation-binary.xml

Spelling in docs

---

src/manual/reporting.md

Swapped the link title and link url.

Link to templates was written wrong.

---

modules/citrus-core/src/main/java/com/consol/citrus/validation/matcher/hamcrest/HamcrestValidationMatcher.java
modules/citrus-core/src/test/java/com/consol/citrus/validation/matcher/hamcrest/HamcrestValidationMatcherTest.java
modules/citrus-integration/src/it/resources/com/consol/citrus/validation/JsonPathValidationIT.xml

Fixes #277. For details, see there.
@christophd The only question which remains is: Does using the List instead of Set break anything?
The tests completed successfully, so I think it won't, but I'm not 100% sure.

Fixes #277 JSONPath validator array length

---

modules/citrus-mail/src/main/java/com/consol/citrus/mail/message/MailMessageConverter.java
modules/citrus-mail/src/main/java/com/consol/citrus/mail/model/BodyPart.java
modules/citrus-mail/src/test/java/com/consol/citrus/mail/message/MailMessageConverterTest.java

MailMessageConverter cannot handle base64 text content

---

.gitignore
modules/citrus-http/src/test/java/com/consol/citrus/http/message/HttpMessageContentBuilderTest.java
modules/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/builder/SendMessageBuilder.java

- Updated .gitignore to discard eclise project configuration files.
- Overload SendMessageBuilder#payload(...) method to accept MultiValueMap
- Added test case for HttpMessageContentBuilder to accept MultiValueMap

(#304) Fixed multipart file upload.

---

modules/citrus-http/src/main/java/com/consol/citrus/http/controller/HttpMessageController.java

The change fixes issue `HttpMessageController is not thread-safe #353`

Update HttpMessageController.java to thread-safely handle response from endpoint adapter

---

src/manual/setup.adoc
src/site/_docs/setup-maven.md
src/site/samples/run/index.html

Hi!
I just exchanged `mvn integration-test` with `mvn clean verify` as mentioned in #362 
BR,
Sven

#362 Corrected documentation concerning maven commands

---

.travis.yml

Hi!
I tested this file in my fork a while ago but the rebase to upstream added a lot of merges etc to the PR. So I just added a branch with the .travis.yml.
BR.
Sven

(#364) Added .travis.yml from my fork

---

tools/test-generator/pom.xml
tools/test-generator/src/main/java/com/consol/citrus/generate/javadsl/JavaDslTestGenerator.java
tools/test-generator/src/main/java/com/consol/citrus/generate/javadsl/JavaTestGenerator.java
tools/test-generator/src/test/java/com/consol/citrus/generate/javadsl/JavaDslTestGeneratorTest.java

I have tried to be oriented towards existing test classes. If I break some code style or I extend the wrong classes, let me know. I will fix it.

Proposal for bug #505

---

.travis.yml
modules/citrus-arquillian/pom.xml

Fixed issue #524 by adding a dependency for 'snakeyaml' in scope 'provided' to citrus-arquillian module

Fixed #524 Initial local build failing in citrus-arquillian

---

.travis.yml
pom.xml
scripts/build.sh

Hi!
This PR is concerning #581. I've simply copied the config from master. I'm currently not sure where sonarcloud gets the branch information from but the [documentation for long-lived branches](https://sonarcloud.io/documentation/branches/long-lived-branches/) does not mention any additional configuration.
Therefore I'd like to give it a try as it is.
*Edit*
I just realized that I named the branch `maintenance/581/add-travis-to-v2.7-bugfix`. :man_facepalming: 
Please don't be confused by this, it was just a little bit early in the morning.
BR,
Sven

(#581) Added sonarcloud config

---

pom.xml
tools/remote/pom.xml

(#584) Updated jackson to version 2.9.8

---

modules/citrus-integration/src/it/java/com/consol/citrus/http/HttpCookieIT.java

PR concerning #455. It seems that the issue was already fixed with #561. Nevertheless, I added the test from the issue to prevent regression.
BR,
Sven

(#455) Cookies are not recognized by http client

---

modules/citrus-integration/src/it/java/com/consol/citrus/jdbc/JdbcExecutionsIT.java
modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/data/DataSetCreator.java
modules/citrus-jdbc/src/main/java/com/consol/citrus/jdbc/server/JdbcEndpointAdapterController.java
modules/citrus-jdbc/src/test/java/com/consol/citrus/jdbc/server/JdbcEndpointAdapterControllerTest.java

This is the second PR concerning https://github.com/citrusframework/citrus-db/issues/36. It is concerning the integration into the Citrus main framework.
BR,
Sven

Enhancement/citrus db/36/add execute batch

---

pom.xml
src/manual/changes-2-7.adoc

Security update for jetty-server

(#639) Updated jetty-server to 9.4.15.v20190215

---

core/citrus-spring/src/main/java/com/consol/citrus/config/xml/SleepActionParser.java

(#775) Altered setter on SleepActionFactoryBean

---

endpoints/citrus-http/src/main/java/com/consol/citrus/http/context/ParentDelegatingWebApplicationContext.java
endpoints/citrus-ws/src/main/java/com/consol/citrus/ws/context/ParentDelegatingWebApplicationContext.java
pom.xml

- Spring Framework 5.3.6
- Apache Camel 3.14.0
- JUnit Jupiter 5.7.2
- Cucumber 6.11.0
- Mockito 3.12.4
- Jackson 2.12.6
- and more

chore(deps): Bump dependency versions

---

endpoints/citrus-camel/src/main/java/com/consol/citrus/camel/actions/CamelActionBuilder.java
endpoints/citrus-camel/src/main/java/com/consol/citrus/camel/actions/StartCamelRouteAction.java
endpoints/citrus-camel/src/main/java/com/consol/citrus/camel/dsl/CamelSupport.java
endpoints/citrus-camel/src/main/resources/META-INF/citrus/action/builder/camel
endpoints/citrus-camel/src/test/java/com/consol/citrus/camel/actions/CamelActionBuilderTest.java
endpoints/citrus-http/src/main/resources/META-INF/citrus/action/builder/http
endpoints/citrus-http/src/test/java/com/consol/citrus/http/actions/HttpActionBuilderTest.java
endpoints/citrus-jms/src/main/java/com/consol/citrus/jms/actions/PurgeJmsQueuesAction.java
endpoints/citrus-jms/src/main/resources/META-INF/citrus/action/builder/purgeQueues
endpoints/citrus-jms/src/test/java/com/consol/citrus/jms/actions/PurgeJmsQueuesActionTest.java
endpoints/citrus-spring-integration/src/main/resources/META-INF/citrus/action/builder/purgeChannels
endpoints/citrus-spring-integration/src/test/java/com/consol/citrus/actions/PurgeMessageChannelActionTest.java
endpoints/citrus-ws/src/main/resources/META-INF/citrus/action/builder/soap
endpoints/citrus-ws/src/test/java/com/consol/citrus/ws/actions/SoapActionBuilderTest.java

Completes test action builder resource lookup used for Groovy runtime

fix(#857): Add test action builder lookup

---

core/citrus-base/src/main/java/com/consol/citrus/container/Wait.java
core/citrus-base/src/main/java/com/consol/citrus/container/WaitActionConditionBuilder.java
core/citrus-base/src/main/java/com/consol/citrus/container/WaitConditionBuilder.java
core/citrus-base/src/main/java/com/consol/citrus/container/WaitFileConditionBuilder.java
core/citrus-base/src/main/java/com/consol/citrus/container/WaitHttpConditionBuilder.java
core/citrus-base/src/main/java/com/consol/citrus/container/WaitMessageConditionBuilder.java
core/citrus-spring/src/main/java/com/consol/citrus/config/xml/WaitParser.java
vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/design/DefaultTestDesigner.java
vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/runner/DefaultTestRunner.java

- Improve constructors to only use builder instead of redundant condition and builder
Fixes #861

fix(#861): Refactor wait action builder

---

connectors/citrus-sql/src/test/java/com/consol/citrus/integration/actions/QueryDatabaseRetriesJavaIT.java
connectors/citrus-sql/src/test/resources/com/consol/citrus/integration/actions/QueryDatabaseRetriesIT.xml
vintage/citrus-java-dsl/src/test/java/com/consol/citrus/integration/design/QueryDatabaseRetriesJavaIT.java
vintage/citrus-java-dsl/src/test/java/com/consol/citrus/integration/runner/QueryDatabaseRetriesTestRunnerIT.java

Avoid racing conditions that cause test to fail on slow environments

chore(build): Fix flaky SQL query retries tests

---

catalog/citrus-bom/pom.xml

fix(#887): Use standalone bom

---

endpoints/citrus-rmi/src/test/java/com/consol/citrus/rmi/server/RmiServerTest.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/actions/ActionsBuilder.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/actions/ActionsConfiguration.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/actions/ActionsScript.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/actions/FinallyActionsBuilder.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/configuration/ConfigurationScript.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/configuration/endpoints/EndpointBuilderWrapper.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/configuration/endpoints/EndpointsConfiguration.java
runtime/citrus-groovy/src/main/java/com/consol/citrus/groovy/dsl/test/TestCaseScript.java
runtime/citrus-groovy/src/test/java/com/consol/citrus/integration/dsl/ActionsScriptIT.java
runtime/citrus-groovy/src/test/java/com/consol/citrus/integration/dsl/ConfigurationScriptIT.java
runtime/citrus-groovy/src/test/resources/com/consol/citrus/groovy/dsl/actions.groovy

- Full support of varArgs and Array method arguments, used in TestActionContainers such as iterate, waitFor, etc. when setting nested test actions via actions() method
- Support doFinally().actions() method calls in addition to using a closure based configuration
- Allow configuration script as alternative to writing a whole test case script

chore: Improve Groovy actions script handling

---

core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java

Detect if the current execution is started from a jar, and if so analyze the jar for resources

---

core/citrus-base/src/test/java/org/citrusframework/actions/ReceiveMessageActionTest.java
core/citrus-base/src/test/java/org/citrusframework/actions/SendMessageActionTest.java
runtime/citrus-groovy/src/test/java/org/citrusframework/groovy/dsl/ReceiveTest.java
runtime/citrus-groovy/src/test/java/org/citrusframework/groovy/dsl/SendTest.java
runtime/citrus-groovy/src/test/java/org/citrusframework/validation/TextEqualsMessageValidator.java
runtime/citrus-groovy/src/test/java/org/citrusframework/validation/script/TemplateBasedScriptBuilderTest.java
runtime/citrus-yaml/src/test/java/org/citrusframework/validation/TextEqualsMessageValidator.java
runtime/citrus-yaml/src/test/java/org/citrusframework/yaml/actions/ReceiveTest.java
runtime/citrus-yaml/src/test/java/org/citrusframework/yaml/actions/SendTest.java

somehow I've lost this changes during some rebase in #959 I think.

ci: windows build fix

---

endpoints/citrus-jms/src/test/resources/org/citrusframework/jms/integration/ReceiveTimeoutIT.xml
src/manual/actions-assert.adoc
src/manual/actions-echo.adoc
src/manual/actions-send.adoc
src/manual/containers-conditional.adoc
src/manual/containers-custom.adoc
src/manual/containers-iterate.adoc
src/manual/containers-repeat-onerror.adoc
src/manual/containers-timer.adoc
src/manual/containers-wait.adoc
src/manual/endpoints.adoc
src/manual/introduction.adoc
src/manual/preface.adoc
src/manual/run-java.adoc
src/manual/runtimes-cucumber.adoc
src/manual/runtimes-junit4.adoc
src/manual/runtimes-junit5.adoc
src/manual/runtimes-testng.adoc
src/manual/runtimes.adoc
src/manual/setup.adoc
src/manual/test-variables.adoc
src/manual/validation-binary.adoc
src/manual/validation-custom.adoc
src/manual/validation-json.adoc
src/manual/validation-schema.adoc
src/manual/validation-xml.adoc

- Typos and grammatical fixes.
- Fixes of two doc section anchors/links.
- Minor issues fixed in code snippets.

#964: Documentation fixes

---

core/citrus-base/src/main/java/org/citrusframework/DefaultTestCaseRunner.java

a must-have for the simulator.

fix: expose test contest to inheritant test case runners

---

validation/citrus-validation-json/src/main/java/org/citrusframework/dsl/JsonSupport.java
validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/schema/JsonSchemaFilter.java
validation/citrus-validation-json/src/test/java/org/citrusframework/validation/json/schema/JsonSchemaFilterTest.java

- No need to catch NoSuchBeanException from Spring here
- Add static DSL entry method for object mapping payload builder

fix(json): Fix unnecessary Spring dependency in Json schema filter

---

core/citrus-base/src/main/java/org/citrusframework/actions/ReceiveMessageAction.java

I found this code, of which I am pretty sure, that it does not belong there. 
Please compare to code on line 227.

fix: Remove duplicate code

---

core/citrus-api/src/main/java/org/citrusframework/TestCaseRunnerProvider.java
core/citrus-api/src/main/java/org/citrusframework/common/TestLoader.java
core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
core/citrus-base/src/main/java/org/citrusframework/DefaultTestCaseRunner.java
core/citrus-base/src/main/java/org/citrusframework/TestCaseRunnerFactory.java
core/citrus-base/src/main/java/org/citrusframework/common/DefaultTestLoader.java
core/citrus-base/src/main/resources/META-INF/citrus/test/runner/default
core/citrus-base/src/test/java/org/citrusframework/TestCaseRunnerFactoryTest.java
core/citrus-spring/src/main/java/org/citrusframework/endpoint/adapter/TestBehaviorExecutingEndpointAdapter.java
runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/CitrusExtensionHelper.java
runtime/citrus-testng/src/main/java/org/citrusframework/testng/TestNGHelper.java

Add a PR for fixing [#1014](https://github.com/citrusframework/citrus/issues/1014)

fix(#1014): Add a mechanism to provide a custom test case runner

---

core/citrus-api/src/main/java/org/citrusframework/TestCaseRunnerProvider.java
core/citrus-base/src/main/java/org/citrusframework/TestCaseRunnerFactory.java
core/citrus-base/src/test/java/org/citrusframework/TestCaseRunnerFactoryTest.java
runtime/citrus-cucumber/src/main/java/org/citrusframework/cucumber/backend/CitrusObjectFactory.java
runtime/citrus-cucumber/src/main/java/org/citrusframework/cucumber/backend/spring/CitrusSpringObjectFactory.java
runtime/citrus-junit/src/main/java/org/citrusframework/junit/JUnit4Helper.java
runtime/citrus-quarkus/citrus-quarkus-runtime/src/main/java/org/citrusframework/quarkus/CitrusTestResource.java

Also fix license headers for new files

fix(#1014): Use testcase runner provider everywhere

---

connectors/citrus-docker/src/main/java/org/citrusframework/docker/command/AbstractDockerCommand.java
connectors/citrus-docker/src/main/java/org/citrusframework/docker/command/ContainerCreate.java
connectors/citrus-docker/src/test/java/org/citrusframework/docker/actions/DockerExecuteActionTest.java

Root issue: https://github.com/citrusframework/citrus/issues/1008

varargs bug fix

---

core/citrus-base/src/main/java/org/citrusframework/main/scan/ClassPathTestScanner.java
core/citrus-base/src/main/java/org/citrusframework/util/FileUtils.java
core/citrus-spring/src/main/java/org/citrusframework/common/SpringXmlTestLoader.java
runtime/citrus-groovy/src/main/java/org/citrusframework/groovy/GroovyTestLoader.java
runtime/citrus-xml/src/main/java/org/citrusframework/xml/XmlTestLoader.java
runtime/citrus-yaml/src/main/java/org/citrusframework/yaml/YamlTestLoader.java
validation/citrus-validation-json/src/main/java/org/citrusframework/json/JsonSchemaRepository.java
validation/citrus-validation-xml/src/main/java/org/citrusframework/xml/XsdSchemaRepository.java
validation/citrus-validation-xml/src/main/java/org/citrusframework/xml/schema/XsdSchemaCollection.java

- XsdSchemaCollection resources
- XsdSchemaRepository resources
- JsonSchemaRepository resources
Relates to #1038

chore: Improve resource resolver mechanism

---

core/citrus-api/src/main/java/org/citrusframework/message/MessageSelector.java
core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
core/citrus-base/src/main/java/org/citrusframework/variable/dictionary/AbstractDataDictionary.java
core/citrus-base/src/test/java/org/citrusframework/variable/dictionary/AbstractDataDictionaryTest.java

a fix for the simulator release, see [the discussion on the simulator PR](https://github.com/citrusframework/citrus-simulator/pull/188#issuecomment-1784761576).

fix: support loading data dictionary from xml

---

core/citrus-spring/src/main/java/org/citrusframework/config/CitrusConversionServiceConfiguration.java
core/citrus-spring/src/main/java/org/citrusframework/config/CitrusSpringConfig.java
core/citrus-spring/src/main/java/org/citrusframework/io/CitrusResourceEditor.java
runtime/citrus-testng/src/main/java/org/citrusframework/testng/spring/TestNGCitrusSpringSupport.java

fix(#1052): Provide ConversionService configuration as extra Configuration class

---

endpoints/citrus-ftp/src/main/java/org/citrusframework/ftp/FtpSettings.java
endpoints/citrus-ftp/src/main/java/org/citrusframework/ftp/message/FtpMarshaller.java
endpoints/citrus-mail/src/main/java/org/citrusframework/mail/MailSettings.java
endpoints/citrus-mail/src/main/java/org/citrusframework/mail/model/MailMarshaller.java

fix(#1057): Add marshaller type environment variable setting

---

endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessageConverter.java
endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageConverterTest.java

this has been around a while. I wonder why this has popped up now @tschlat. but it indeed seems to be an issue, report in https://github.com/citrusframework/citrus-simulator/issues/218.

fix: cookie on http response with status code

---

connectors/citrus-selenium/src/main/java/org/citrusframework/selenium/actions/FillFormAction.java
connectors/citrus-selenium/src/main/java/org/citrusframework/selenium/actions/SeleniumActionBuilder.java
connectors/citrus-selenium/src/main/java/org/citrusframework/selenium/actions/SetInputAction.java
connectors/citrus-selenium/src/main/java/org/citrusframework/selenium/xml/FillForm.java
connectors/citrus-selenium/src/main/java/org/citrusframework/selenium/xml/Selenium.java
connectors/citrus-selenium/src/main/java/org/citrusframework/selenium/yaml/FillForm.java
connectors/citrus-selenium/src/main/java/org/citrusframework/selenium/yaml/Selenium.java
connectors/citrus-selenium/src/test/java/org/citrusframework/selenium/actions/FillFormActionTest.java
connectors/citrus-selenium/src/test/java/org/citrusframework/selenium/groovy/SeleniumTest.java
connectors/citrus-selenium/src/test/java/org/citrusframework/selenium/xml/SeleniumTest.java
connectors/citrus-selenium/src/test/java/org/citrusframework/selenium/yaml/SeleniumTest.java
connectors/citrus-selenium/src/test/resources/org/citrusframework/selenium/groovy/selenium.test.groovy
connectors/citrus-selenium/src/test/resources/org/citrusframework/selenium/xml/selenium-test.xml
connectors/citrus-selenium/src/test/resources/org/citrusframework/selenium/yaml/selenium-test.yaml
runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase-4.1.0-SNAPSHOT.xsd
runtime/citrus-xml/src/main/resources/org/citrusframework/schema/xml/testcase/citrus-testcase.xsd
src/manual/endpoint-selenium.adoc

- Action fills multiple form fields with given values
- Optionally submits form after fields have been set

Add fill form Selenium test action

---

endpoints/citrus-http/src/main/resources/org/citrusframework/schema/citrus-http-testcase.xsd

left-over from the spring migration.

remove comment and version from http xsd schema

---

endpoints/citrus-ftp/src/main/java/org/citrusframework/ftp/server/SftpServer.java

- Take care of non Unicode characters that get created on FTPS server for a remote file handle
- Avoid to break the XML/JSON marshal serialization of incoming put commands
Fixes #1107

fix(#1107): Support non Unicode remote file handle on SFTP server

---

core/citrus-base/src/main/java/org/citrusframework/sharding/Shard.java
core/citrus-base/src/test/java/org/citrusframework/sharding/ShardTest.java
core/citrus-base/src/test/java/org/citrusframework/sharding/ShardingConfigurationTest.java
src/manual/runtimes-junit5.adoc
src/manual/runtimes-testng.adoc

see the original commit 6840b5b8dcb8de690844f03d28c85d3dad666c13 for information about configuration, parameters etc.

feat(testng): shard data provider tests

---

runtime/citrus-cucumber/src/main/java/org/citrusframework/cucumber/backend/spring/CitrusSpringObjectFactory.java

- Citrus Cucumber Spring object factory must create new test context instance for each scenario
- Using a singleton test context instance for all scenarios leads to unexpected behavior (e.g. when exceptions are added to the test context)
Fixes #1115

fix(#1115): Create new test context for each Cucumber scenario

---

connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesExecuteIT.xml
connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesSendReceiveIT.xml
endpoints/citrus-http/src/main/java/org/citrusframework/http/client/HttpClient.java
endpoints/citrus-http/src/main/java/org/citrusframework/http/server/HttpServer.java
endpoints/citrus-http/src/test/java/org/citrusframework/http/config/annotation/HttpServerConfigParserTest.java
endpoints/citrus-http/src/test/java/org/citrusframework/http/config/xml/HttpServerParserTest.java
endpoints/citrus-http/src/test/java/org/citrusframework/http/server/HttpServerTest.java
endpoints/citrus-ws/src/main/java/org/citrusframework/ws/server/WebServiceServer.java
endpoints/citrus-ws/src/test/java/org/citrusframework/ws/config/annotation/WebServiceServerConfigParserTest.java
endpoints/citrus-ws/src/test/java/org/citrusframework/ws/config/xml/WebServiceServerParserTest.java
pom.xml

dependency updates

---

core/citrus-api/pom.xml
core/citrus-api/src/main/java/org/citrusframework/TestCase.java
core/citrus-api/src/main/java/org/citrusframework/TestResult.java
core/citrus-api/src/main/java/org/citrusframework/context/TestContext.java
core/citrus-api/src/main/java/org/citrusframework/report/TestReporters.java
core/citrus-api/src/main/java/org/citrusframework/report/TestResults.java
core/citrus-api/src/main/java/org/citrusframework/spi/PropertiesLoader.java
core/citrus-api/src/test/java/org/citrusframework/TestResultTest.java
core/citrus-api/src/test/java/org/citrusframework/report/TestReportersTest.java
core/citrus-base/src/main/java/org/citrusframework/DefaultTestCase.java
core/citrus-base/src/main/java/org/citrusframework/common/DefaultTestLoader.java
core/citrus-base/src/main/java/org/citrusframework/report/JUnitReporter.java
core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
core/citrus-base/src/test/java/org/citrusframework/DefaultTestCaseTest.java
core/citrus-base/src/test/java/org/citrusframework/message/ZipMessageTest.java
core/citrus-base/src/test/java/org/citrusframework/report/JUnitReporterTest.java
core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
core/citrus-base/src/test/java/org/citrusframework/report/TestResultsTest.java
core/pom.xml
runtime/citrus-cucumber/src/main/java/org/citrusframework/cucumber/CitrusLifecycleHooks.java
runtime/citrus-cucumber/src/test/java/org/citrusframework/cucumber/backend/CitrusLifecycleHooksTest.java
runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/CitrusExtension.java
runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/spring/CitrusSpringExtension.java

measurement of individual test case and suite execution time.

test case execution time measurement

---

connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java
connectors/citrus-openapi/src/test/java/org/citrusframework/openapi/model/v3/Oas30ModelHelperTest.java

Fix: NPE in case of response header without required attribute

---

core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
core/citrus-spring/src/main/java/org/citrusframework/spi/SpringResourceWrapper.java

I've tested the fix within the project where the problem first occurred.
relevant resources:
* https://bugs.openjdk.org/browse/JDK-8314511
closes #1200.

citrus api on windows hosts

---

tools/archetypes/jms/src/main/resources/archetype-resources/pom.xml
tools/archetypes/quickstart/src/main/resources/archetype-resources/pom.xml
tools/archetypes/soap/src/main/resources/archetype-resources/pom.xml

testng in archetypes

---

core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java

fix(#1204): ignore file system recovery for nested citrus api resources

---

validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/XmlMarshallingValidationProcessor.java
validation/citrus-validation-xml/src/test/java/org/citrusframework/validation/xml/XmlMarshallingValidationProcessorTest.java

I came across this bug and supply a fix for it.

Include unmarshaller in Validation Processor

---

src/manual/introduction.adoc

closes https://github.com/citrusframework/citrus/issues/1186

mention kotlin support in docs

---

connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/KubernetesActor.java
connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/KubernetesActorTest.java
connectors/citrus-testcontainers/src/main/java/org/citrusframework/testcontainers/TestcontainersActor.java
connectors/citrus-testcontainers/src/test/java/org/citrusframework/testcontainers/TestcontainersActorTest.java
core/citrus-api/src/main/java/org/citrusframework/TestActor.java
core/citrus-api/src/test/java/org/citrusframework/TestActorTest.java
src/manual/test-actors.adoc

fix(#1275): Add environment setting to enable/disable test actors

---

endpoints/citrus-http/src/main/java/org/citrusframework/http/client/HttpResponseErrorHandler.java

original: https://github.com/citrusframework/citrus/pull/1224/commits/1a2072928dad5f8b01f916c4972d192316a2169a

throwsException strategy throws stack overflow exception

---

connectors/citrus-knative/src/main/java/org/citrusframework/knative/actions/messaging/CreateSubscriptionAction.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/integration/DeleteKnativeResourceIT.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/integration/KnativeServiceConfiguration.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/integration/VerifyKnativeBrokerIT.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/xml/AbstractXmlActionTest.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/xml/DeleteResourceTest.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/xml/DeleteSubscriptionTest.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/xml/VerifyBrokerTest.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/yaml/AbstractYamlActionTest.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/yaml/DeleteResourceTest.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/yaml/DeleteSubscriptionTest.java
connectors/citrus-knative/src/test/java/org/citrusframework/knative/yaml/VerifyBrokerTest.java
connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/client/KubernetesClient.java
connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/xml/K8sClientConfig.java
connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/xml/KubernetesClientParser.java
connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/KubernetesActorTest.java
connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/integration/KubernetesServiceConfiguration.java
connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/xml/AbstractXmlActionTest.java
connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/yaml/AbstractYamlActionTest.java
connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesExecuteIT.xml
connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesSendReceiveIT.xml
pom.xml

noteable breaking change included:
* `io.fabric8` from 6.13.4 to 7.0.1

fix(deps): updated dependency versions

---

runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/JUnitJupiterEngine.java

Do not reigster empty listeners

---

.github/workflows/build.yml
.github/workflows/lts.yml
connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/KubernetesActor.java
connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/KubernetesSettings.java
connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/actions/AbstractKubernetesAction.java
connectors/citrus-testcontainers/src/test/java/org/citrusframework/testcontainers/TestcontainersActorTest.java

- Use default Kubernetes test actor only when feature is enabled

fix(#1290): Fix default Kubernetes actor

---

core/citrus-base/src/main/java/org/citrusframework/actions/CreateVariablesAction.java

- Test variables support any type of value, make sure that the create-variables action DSL can set any value instead of just String

chore: Support Object type value in create variables

---

endpoints/citrus-http/src/main/java/org/citrusframework/http/config/annotation/HttpServerConfig.java
endpoints/citrus-http/src/main/java/org/citrusframework/http/config/annotation/HttpServerConfigParser.java
endpoints/citrus-http/src/main/java/org/citrusframework/http/server/AbstractHttpServerBuilder.java
endpoints/citrus-http/src/main/java/org/citrusframework/http/server/HttpServer.java
endpoints/citrus-http/src/main/java/org/citrusframework/http/server/HttpServerSettings.java
endpoints/citrus-websocket/src/main/java/org/citrusframework/websocket/config/annotation/WebSocketServerConfig.java
endpoints/citrus-websocket/src/main/java/org/citrusframework/websocket/config/annotation/WebSocketServerConfigParser.java

- New option to add custom Http servlet filters on top of default servlet filters (e.g. request caching filter)

chore: Use default Http servlet filters option

---

pom.xml
tools/agent/pom.xml
tools/agent/src/main/java/org/citrusframework/agent/CitrusAgentApplication.java

Issue/1347: Set `System.out` to a log4j-managed `PrintStream`

---

runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/CitrusTestFactorySupport.java
runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/JUnitJupiterEngine.java
runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/main/JUnitCitrusTest.java
tools/agent/src/main/java/org/citrusframework/agent/util/ConfigurationHelper.java
tools/jbang/src/main/java/org/citrusframework/jbang/commands/Run.java

fix(#1367/#1368): Citrus JBang test engine and running multiple sources with JUnit5
